### ISSUE TITLE
Add support for array of children

### ISSUE THREAD

**Issue by vorg** [thi-ng/umbrella#11]
Tag: hiccup-dom

The following code

```javascript
var grid = require('grid-cells')
var cells = grid(1024, 512, 4, 2, 10);
var parent = ["div", {}]
parent.push(['svg', { width: 512, height: 512 },
  cells.map((cell, index) => {
        var i = index % nx
        var j = Math.floor(index / nx)
        return ['rect', { x: cell[0], y: cell[1], width: cell[2], height: cell[3] }]
     })
  ])
```

Creates data as follows

<img width="527" alt="screen shot 2018-02-23 at 17 09 40" src="https://user-images.githubusercontent.com/171001/36606810-b820912c-18bc-11e8-900d-54d5ef5947f0.png">

And fails with error

<img width="348" alt="screen shot 2018-02-23 at 17 13 04" src="https://user-images.githubusercontent.com/171001/36606862-ddf5ba9e-18bc-11e8-9ad5-aae1fe9e5304.png">

That's because svg first child is an array of items

```javascript
var element = ["svg", {}, [
 ["rect", {}], ["rect", {}], ["rect", {}], ...
]
```

which hiccup seems to interpret as invalid element without name.

The are multiple possible fixes at the moment:

### 1. Use spread to unnest array

```javascript
...cells.map((cell, index) => {
}
```

as it produces

<img width="231" alt="screen shot 2018-02-23 at 17 14 54" src="https://user-images.githubusercontent.com/171001/36606954-18e8b4ee-18bd-11e8-9131-ba7100a3ea4e.png">

### 2. Push or reduce to an array initialized with a wrapper tag name

```javascript
  cells.reduce((children, cell, index) => {
        var i = index % nx
        var j = Math.floor(index / nx)
        children.push(['rect', { x: cell[0], y: cell[1], width: cell[2], height: cell[3] }])
        return children
     }, ["g"])
```

as it produces

<img width="214" alt="screen shot 2018-02-23 at 17 17 29" src="https://user-images.githubusercontent.com/171001/36607076-77a95240-18bd-11e8-9f3d-4a76bf062c3a.png">

**Comment by postspectacular** [comment]
Thanks, Marcin - yes this is one of the differences between the hiccup & hiccup-dom implementations, which are briefly mentioned in the readme. I've tried to address this in the past but it's rather non-trivial and I had to defer it. Currently I recommend using the spread op for these cases, but realize this adds an unnecessary overhead. Will take another stab at this soon. Changes will need to be made to these functions: `normalizeTree`, `diffElement` & `createDOM`

**Comment by postspectacular** [comment]
@vorg - I think this should be working now, but please do let me know if you run into issues. Here's the modified code I've tried it with:

```js
function app() {
    var cells = grid(512, 512, 64, 64, 1);
    return ["div",
        ['svg', { width: 512, height: 512 },
            cells.map(([x, y, width, height]) => ['rect', { x, y, width, height }])]
    ];
}

start("app", app());
```
