### ISSUE TITLE
[router] Browser Back Button Not Working

### ISSUE THREAD

**Issue by loganpowell** [thi-ng/umbrella#129]
I'm using `create-hdom-app` and having some issues with the browser back button. Not sure if I should have posted this there, but I believe it's an issue with the router:

Here's the router config from the test repo:

https://github.com/loganpowell/testing_hdom-app/blob/master/src/config.ts#L16

Here's the behavior with default settings from `yarn create hdom-app <my app>`:

![hash_history](https://raw.githubusercontent.com/loganpowell/testing_hdom-app/master/clips/hash_history.gif)

and if I change the config to:
```js
...
 router: {
      useFragment: false,
      defaultRouteID: "home",
      initialRouteID: "home",
      separator: "/",
      prefix: "/",
      routes: [
          routes.HOME,
          routes.TEST,
      ]
    },
...
```
it __sorta__ fixes the back button, but then weird hashes show up during back navigation:

![html5_history](https://raw.githubusercontent.com/loganpowell/testing_hdom-app/master/clips/html5_history.gif)

Thoughts?

**Comment by postspectacular** [comment]
Hey @loganpowell - this weird behavior is explainable: In the example only the these 2 routes are defined: `/test/1` & `/test/2` - the last one used (`/test/3`) is explicitly configured to [fail route validation]() and hence will be redirected by the router to the configured default route `/home` - when you press the back button from that state, then the browser will try to go back to `/test/3` which again then redirects to `/home` - hence the strange behavior. Having said this, it might make sense to use `location.replace()` to handle these forced redirects...

**Comment by postspectacular** [comment]
Btw. For some more reference & commented sources, also do checkout the [router-basics example](../tree/master/examples/router-basics/)

**Comment by loganpowell** [comment]
thank you sir
