### ISSUE TITLE
[rstream] - Accept three functions as arguments in subscribe

### ISSUE THREAD

**Issue by allforabit** [thi-ng/umbrella#134]
It would help with interop with standard Ecmascript observables if the `subscribe` function used in rstream accepted three functions, the first one for the next value, the second for error handling and the final one to indicate that it's done.  Do you think this would have much of a knock on effect?  Apart from this it looks pretty much compatible with the standard: https://github.com/tc39/proposal-observable

**Comment by allforabit** [comment]
For now I'm wrapping it using this:

```
const wrapRStream = (s: ISubscribable<any>) => {
  return {
    subscribe: (next, error, done) => {
      const sub = s.subscribe({
        next,
        error,
        done
      });
      return sub;
    }
  };
};

```

**Comment by postspectacular** [comment]
Hey @allforabit - this sounds feasible & I agree that'd be a nice feature, but so far I know close to nothing about that TC39 proposal, so will first have to read up on it... give me a few days! :)

**Comment by allforabit** [comment]
I'm thinking it's probably just as handy to use simple functions to go between observables and rstream so feel free to close this. 

Maybe it'd be useful to include these snippets in the wiki to go between rstream and observables?
```
import { ISubscribable, stream } from "@thi.ng/rstream";

export const toObservable = (s: ISubscribable<any>) => {
  return {
    subscribe: (next, error, done) => {
      return s.subscribe({
        next,
        error,
        done
      });
    }
  };
};

export const fromObservable = obs =>
  stream(o => {
    obs.subscribe({
      next(v) {
        o.next(v);
      },
      error(e) {
        o.error(e);
      },
      complete() {
        o.done();
      }
    });
  });
```
I'm not really sure of the feasibility of making them compatible in any case as observables are expecting the subscribe function to receive the `next`, `error` and `done` callbacks and in rstream a function is assumed to be a transducer.

**Comment by allforabit** [comment]
Closing in favour of https://github.com/thi-ng/umbrella/issues/246
