### ISSUE TITLE
Can you share igs export Sample Code?

### ISSUE THREAD

**Issue by selvakarna** [thi-ng/umbrella#136]
Can you share igs export Sample  Code?

**Comment by postspectacular** [comment]
Did you have a look at the readme example? ([here](https://github.com/thi-ng/umbrella/blob/master/packages/iges/README.md#usage-examples))

**Comment by postspectacular** [comment]
So was that helpful or not? A bit more context (esp. w/ something complex like IGES) would have been helpful...
