### ISSUE TITLE
[malloc][Feature Request] Save the allocator data in the ArrayBuffer itself

### ISSUE THREAD

**Issue by Bnaya** [thi-ng/umbrella#138]
Intro: 
I'm writing a library that gives object api(read & write), but that data is saved inside an ArrayBuffer.
All of the operation data is saved inside the ArrayBuffer, so its possible to pass the ArrayBuffer to a WebWorker or even to use SharedArrayBuffer, and it will work on the other side
The current implementation doesn't have full allocator, but append/simple overwrite.
https://github.com/Bnaya/objectbuffer

I was thinking to write an allocator, and i came across this library, it looks great, but saves the allocator auxiliary data on the javascript side, and not in the arraybuffer.

I will start trying to do it myself.

Thank you for umbrella project!

**Comment by postspectacular** [comment]
Hey @Bnaya - this is an interesting proposal and shouldn't be too hard to implement. Though, before you start you might also want to check out [tinyalloc](https://github.com/thi-ng/tinyalloc), upon which this TS version is based on, but could be compiled to WASM and then already implements this. You'd only need to write a bit of JS glue code/frontend for it...

Ps: If you go down this route, be aware there's an [outstanding PR](https://github.com/thi-ng/tinyalloc/pull/6) which I've yet to deal with/verify and which impacts the allocators internal structure...

**Comment by postspectacular** [comment]
Another side question: I was under the impression that `SharedArrayBuffer` had been suspended in Chrome/FF - is that coming back again?

**Comment by Bnaya** [comment]
The blocker for `SharedArrayBuffer` is site process isolation.

chrome desktop has it, so it's enabled there. see demo: 
https://codesandbox.io/s/objectbuffer-demo-sharedarraybuffer-tf3il?fontsize=14&module=%2Fsrc%2Findex.ts

Due to memory overhead, it's not enabled yet for chrome for android.

Firefox is expected to have site process isolation on soon, and [i believe they will re-enable SAB not long after](https://bugzilla.mozilla.org/show_bug.cgi?id=1477743)

**Comment by Bnaya** [comment]
Regarding the wasm idea,
TBH i'm not sure what would be the implications

I prefer to have all the code to be bundled to a single file, and that i could use the allocator synchronously.
And also, i want it to be useable on any given ArrayBuffer/SharedArrayBuffer and not only wasm memory.
And i have the feeling that wasm wont allow it. but its very possible that i'm mistaken

**Comment by postspectacular** [comment]
Hey, by all means, this was just an idea and didn't mean to imply that you should go this way... :)

As for your other points:

- synchronous WASM use: it's possible (especially with such small modules, tinyalloc is ~1.5KB) and could be done like this: https://github.com/thi-ng/umbrella/blob/feature/simd/packages/simd/src/index.ts#L29
- use any ArrayBuffer: see same example from prev point, which asks for user supplied memory (`WebAssembly.Memory` is just a wrapper around an ArrayBuffer).
- SharedArrayBuffer: pretty much the same, only you'd add `shared: true` as ctor option for the WASM memory instance

```js
mem= new WebAssembly.Memory({
  initial: 1,
  maximum: 8,
  shared: true
});

mem.buffer
// SharedArrayBuffer(65536) {}
```

Obviously, this doesn't work with pre-existing ArrayBuffers, shared/unshared, but I don't know enough about the usage patterns of your lib... anyhow, really just food for thought. Regardless, changing the TS version (your original question) wouldn't be too much work, but you'll have to think about reserving address space for the allocator data and how to manage and/or clamp growth. Right now the main difference between tinyalloc and the TS version is that the former has a hard (but configurable) limit on the number of allocated regions (regardless of their size, remaining space).

**Comment by Bnaya** [comment]
Thanks for the info!
So i've decide to go for the typescript version,
I'm gonna try to create MemBlock class that encapsulate the read/writes to the arraybuffer
Do you have maybe another approach i should try?

**Comment by Bnaya** [comment]
So, actually it worked :)
https://github.com/thi-ng/umbrella/pull/153/files
