### ISSUE TITLE
[hiccup-svg] svg.image is not exported

### ISSUE THREAD

**Issue by vorg** [thi-ng/umbrella#142]
SVG image tag defined in [image.ts](https://github.com/thi-ng/umbrella/blob/master/packages/hiccup-svg/src/image.ts) is not exported in [index.ts](https://github.com/thi-ng/umbrella/blob/master/packages/hiccup-svg/src/index.ts) causing `svg.image([x, y], url)` to crash with `undefined function`

**Comment by postspectacular** [comment]
Hey @vorg - thanks for finding this. So far only used that function implicitly via `convertTree()`, but will release fix in the next few days (along with other updates)...
