### ISSUE TITLE
[malloc][RFC/IDEA] calloc should zero-fill only when re-using a block

### ISSUE THREAD

**Issue by Bnaya** [thi-ng/umbrella#155]
A new ArrayBuffer is guaranteed to be zero initialized [ref](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer#Return_value)

`malloc` knows if it has allocated fresh memory, or re-use a block **

`calloc` can use that info to decide if it should to set zeros, or not.

possible issues:
** the user might provider an ArrayBuffer, that is "dirty"
** There's an issue when `compact` merged memory back into `top`, so it will require addressing

**Comment by postspectacular** [comment]
I like that idea! How about:

- add config option, e.g. `alwaysZeroFill` (default: false) to `MemPoolOpts` and explain in the docstring that if providing an ArrayBuffer it's user's responsibility to ensure it's clean or else set this option to true
- the merge-with-top case during compaction should be easy enough to check for, but good thinking! 👍

**Comment by postspectacular** [comment]
Closing. Superseded by [different behavior in [v4.1.0](https://github.com/thi-ng/umbrella/blob/develop/packages/malloc/CHANGELOG.md#410-2019-11-09)
