### ISSUE TITLE
[hiccup-markdown] resolve interaction of inline formats and newlines

### ISSUE THREAD

**Issue by loganpowell** [thi-ng/umbrella#156]
Hi @postspectacular 

I'm smashing my head against this and I'm sure there's a simple explanation or I'm just doing something dumb, but...

In your `hiccup-markdown` [example](https://github.com/thi-ng/umbrella/tree/master/examples/markdown), I'm trying to recreate it, but when I try to use a file string read via `fs.readFileSync` call (with `utf8` encoding) the result is an empty `[]` rather than a hiccup tree:

```js
const blog = readFileSync('./assets/blog.md', 'utf8')
console.log([...iterator(parse(), blog)]) //? -> []
```

It works perfectly (both in console and rendered in hiccup within hdom `start()`) if the string is stored as a standard `var/let/const`. but not when I try to load it in as a file. I can't figure out what I'm doing wrong. When I print/log/return the variable wherein I store the result of `readFileSync` - the markdown is printed. I just can't figure out why the iterator isn't parsing it...

Why? I'm trying to figure out how best to script this up so that I can dynamically load static markdown files (e.g., from `assets/`) as plain strings that can be used by `iterator`.

I also tried to use your [Parcel setup](https://github.com/thi-ng/umbrella/blob/master/examples/markdown/package.json): 
```js
    "scripts": {
... // is this (--global md) where the magic happens:?
        "build-parser": "yarn clean && parcel build src/parser.ts -d out --global md --public-url ./ --no-source-maps --no-cache --experimental-scope-hoisting --detailed-report --experimental-scope-hoisting",
... 
    },
```
...but I noticed you [`.gitignored` the `*.js` files](https://github.com/thi-ng/umbrella/blob/master/examples/markdown/.gitignore)

I'm stuck.

Two questions:
1. is there a better way than using `readFile` from node with Parcel to turn the file string into an iterable that can be consumed by `iterator`?
2. Should I forgo HDOM's `start()` in favor of `transducers-hdom`? I recall you mentioning you prefer using streams rather than RAF/interceptors. It would help me if you have some guidance as what the pros/cons are for the various approaches

**Comment by postspectacular** [comment]
Hmm.. not sure what's going on here. I just tried this myself (in the node REPL) and it seems to work:

```js
// md-debug.js
const md = require("@thi.ng/hiccup-markdown");
const tx = require("@thi.ng/transducers");
const fs = require("fs");

const src = fs.readFileSync("examples/markdown/README.md", "utf8");
console.log([...tx.iterator(md.parse(), src)]);
```

```
node md-debug.js 
[
  [ 'h1', ' Minimal Markdown parser ' ],
  [
    'p',
    'This project is part of the ',
    [ 'a', [Object], '@thi.ng/umbrella' ],
    ' monorepo. '
  ],
  [ 'h2', ' About ' ],
  [
    'p',
    'This example is a test environment for the new & minimal ',
    [ 'a', [Object], 'Markdown' ],
    ' parser & converter to ',
    [ 'a', [Object], 'hiccup' ],
    ' format from the ',
    [ 'a', [Object], '@thi.ng/hiccup-markdown' ],
    ' package. '
  ],
 ...
]
```

I'm somewhat confused how you'd use `fs.readFileSync()` with Parcel, but at the same time are asking in the context of hdom, so i'm assuming this is in the browser, yes? Could you please post your example (e.g. a gist)?

As for that `--global md` - I've got no idea what I was thinking there, must be some left over remains of some experiment... 99% sure this isn't used or relevant here

And re: `start()` vs `updateDOM()` - recently I've been largely using the latter, but its use is not precluding interceptors/atoms and in fact I found it useful to compartmentalize different parts of state updates and the resulting transformations (derived view creations). So still using an atom as single source of truth, interceptors for event processing and triggering atom updates, then rstream pipelines attached to different branches of the atom's state value to drive transformations and eventually update the UI (but only do so when needed)...

**Comment by nkint** [comment]
Hi @loganpowell 

I use this code in [runjs](https://runjs.dev):

```ts
import fs from 'fs'
import {iterator} from '@thi.ng/transducers'
import { parse } from "@thi.ng/hiccup-markdown";

const blog = fs.readFileSync('/tmp/foo.md', 'utf8')
console.log(blog)
console.log([...iterator(parse(), blog)])
```

where content of `/tmp/foo.md` is:
```md
# title

body```

and my output is correct:
```
[ [ 'h1', ' title ' ] ]
```

So seems there are no problem here

**Comment by nkint** [comment]
(@postspectacular did the answer first ;)

**Comment by postspectacular** [comment]
@nkint you win, i got side tracked... :)

**Comment by postspectacular** [comment]
Could it be that Parcel is transforming referenced .md files as part of the bundling process? I just look at the example again and there I'm importing `README.txt` (not `README.md`). Could be the reason, but can't check right now...

**Comment by loganpowell** [comment]
🤔 I have no idea why this isn't working for me. Yes, I'm using Parcel and doing this in the browser, just used the `console` example to keep it short. In the browser, it's not rendering anything (not even an empty div or anything).

As for why `readFile`, Parcel [will actually use these to parse and instantiate the file](https://github.com/parcel-bundler/parcel/issues/970#issuecomment-381403710) via given calls.

Let me see if I can change up the dev env a bit. That looks like it may be the issue. Thank you both so much for looking into this for me. At least I know it's supposed to work!

**Comment by nkint** [comment]
Hi @loganpowell I don't know how parcel handle this but honestly IMHO is not the best idea ever to use filesystem functions in the browser even if a specific version of the bundler can handle it... 
Some different thought if you're building server-side-rendering app or if you're treating them as static asset but in that case parcel can handle differently without the need of `fs` node module at all, I think.

**Comment by loganpowell** [comment]
@nkint I totally agree with you. I was just trying to get started and hit a road block. I mean to look into a more robust static `.md` file handling solution with Parcel, I just wanted to see my `md` -> `hiccup` :). Might you have a resource for a better Parcel solution for this?

**Comment by postspectacular** [comment]
@loganpowell you can directly `import` asset files into your source and Parcel will resolve them for you as URL. Though, because MD assets are auto-transformed by Parcel (and I don't know how to disable this), I've resorted to renaming the `.md` file(s) to `.txt` and this then just works:

```ts
import readme from "../README.txt";

// readme's value is just a URL
fetch(readme).then((res) => res.text()).then(() => yadayada...)
```

To avoid the error highlight for that txt import, you can add a declaration file like this to the `/src` folder:

e.g. save as `/src/assets.d.ts`:

```ts
declare module "*.txt";
declare module "*.png";
declare module "*.jpg";
```

**Comment by loganpowell** [comment]
@postspectacular thank you for that. I am digging deeper into this and I made this example:

https://codesandbox.io/s/jovial-dew-6wpz9

it's not working for me here either 😢 

What am I doing wrong?

I can create an even more slimmed down version if so desired...

**Comment by loganpowell** [comment]
Ok, I've narrowed it down a bit.

It seems that part of the issue is that - in Windows - in order to make it work, I have to use `LF` (`\n`) instead of `CRLF` (`\r\n`) and - for the most part - it works with this change. I can give this fix a go if you'd like as many teams just use carriage return as it's cross-platform (including codesandbox):

However, regardless of whether I use Carriage Return or regular Line Feed, I need to add a trailing empty new line to get the last group of markdown (characters/lines) to be parsed. See the interactive example below

https://codesandbox.io/s/confident-pike-ezhf4

**Comment by postspectacular** [comment]
That'd make sense, but bloody windows linefeeds! It's should be fine to just compose `parse()` with a pre-filter for `\r` chars:

```ts
[...tx.iterator(md.parse(), `# hi\r\n\r\nfoo\r\n\r\n`)]
// []

[...tx.iterator(tx.comp(tx.filter((x)=>x!=`\r`),md.parse()), `# hi\r\n\r\nfoo\r\n\r\n`)]
// [ [ 'h1', ' hi ' ], [ 'p', 'foo ' ] ]
```

But that should be done internally (by updating `parse()` itself) - i can/will do that...

That trailing extra line is currently required because the parser only processes one char at a time and is reading from an iterable, without knowledge of more inputs coming. And due to the way line breaks are interpreted in MD, it's not sufficient to just have a single line break at the end - a paragraph is only finished when reading 2 consecutive ones...

It's not hard though to invoke like this though:

```ts
src = "# hi\r\n\r\nthere...\r\n`

[...tx.iterator(tx.comp(tx.filter((x)=>x!=`\r`),md.parse()), src + "\n")]
```

**Comment by loganpowell** [comment]
Thank you sir! One more thing, for some reason the `>` character (blockquote) breaks the parser.

**Comment by loganpowell** [comment]
Everything now works as expected 🙏

**Comment by loganpowell** [comment]
Not sure if this is a bug, but - currently - I have to add 3x `\n` (newline) for two adjacent paragraphs to be split into separate `["p"...]` components. E.g., :

This doesn't work:
```
Herz sich nennt erfreuet dunst tränen die. Den zauberhauch lispelnd lied gestalten gezeigt. Nun das ihr halbverklungnen besitze  steigen menge ihr der. 

Besitze das gesänge die geisterreich mein die, nebel und herz früh was ihr wahn, hören sie das nach vom festzuhalten und stillen hören sich. Einer vom gleich.
```
this does:
```
Herz sich nennt erfreuet dunst tränen die. Den zauberhauch lispelnd lied gestalten gezeigt. Nun das ihr halbverklungnen besitze  steigen menge ihr der. 


Besitze das gesänge die geisterreich mein die, nebel und herz früh was ihr wahn, hören sie das nach vom festzuhalten und stillen hören sich. Einer vom gleich.
```

**Comment by postspectacular** [comment]
Hi @loganpowell - off the top of my head I can't quite say if this is something which is related to the recent updates, but I can't replicate this issue in the latest `develop` version:

```ts
[...tx.iterator(m.parse(), `hello\n\nthere\n\n`)]
// [ [ 'p', 'hello ' ], [ 'p', 'there ' ] ]

[...tx.iterator(m.parse(), `hello\r\n\r\nthere\r\n\r\n`)]
// [ [ 'p', 'hello ' ], [ 'p', 'there ' ] ]
```

**Comment by loganpowell** [comment]
Thank you! It must be something on my end...

**Comment by loganpowell** [comment]
I think it breaks when you add an exclamation point to the end of a paragraph.

Try:

```js
[...tx.iterator(m.parse(), `hello!\n\nthere\n\n`)]
```
example:
https://codesandbox.io/s/confident-pike-ezhf4

**Comment by postspectacular** [comment]
Thanks @loganpowell - this probably has to do with inline element/style parsing and the fact that `!` is a partial match for `![` (image tag)... will take a deeper look! FWIW I was just about to release a bunch new updates (incl. the updates done to this package), but if this is something which isn't too obvious to fix tonight, then a fix for this new issue will probably only be coming later, since I don't want this to hold off everything else...

**Comment by loganpowell** [comment]
No worries _at all_. I'm actually amazed with what you've done using a transducer. Finite state machine as an xform, was that your idea?

**Comment by postspectacular** [comment]
I've done some more testing and can confirm that the issue has to do with an interaction with partially matched inline format symbols. I've updated the readme to link to this issue, but the fix is more involved and so will only be part of a future release...

@loganpowell - that's exactly right. The FSM transducer is essentially a collection of user provided transformation functions of which always only one will be active and which delegate to responsibility to each other based on incoming input values. For each input, the transducer might do any combination of:

- consume input
- trigger internal state change
- produce a transformed result for external downstream processing

Parsing is just one example of this, but my initial impetus for this was event processing (as yet another alternative to explore in addition to interceptors etc.)

**Comment by loganpowell** [comment]
> Parsing is just one example of this, but my initial impetus for this was event processing (as yet another alternative to explore in addition to interceptors etc.)

Indeed I can see the potential for this!

**Comment by postspectacular** [comment]
Closing. Parser was completely rewritten for [v3.0.0](https://github.com/thi-ng/umbrella/blob/develop/packages/hiccup-markdown/CHANGELOG.md#300-2023-02-27)
