### ISSUE TITLE
[RFC] modernize tests toolchain

### ISSUE THREAD

**Issue by Bnaya** [thi-ng/umbrella#158]
The current test infra has some limitations:

* Requires build of the tests and source code
* No watch mode
* no sourcemaps
  * inaccurate coverage?
* Due to all of that, debug is cumbersome 
* uses mocha ;)

a quick win for most of these problems would be to use ts-node/register
```
"test": "TS_NODE_PROJECT=test/tsconfig.json node -r ts-node/register ./node_modules/.bin/mocha test/*.ts --watch-extensions ts",
"test-debug": "TS_NODE_PROJECT=test/tsconfig.json node -r ts-node/register --inspect-brk ./node_modules/.bin/mocha test/*.ts",
```
Can be done also via `mocha.opts`

Action item for me:
Make a draft pr for at least one package with the proposed change, to see if we want to go on with that

Additionally:
ts3.7 should make it easier to setup project references for zero-build tests (not even the libs the tested code is importing)   

For the long run, i think jest is a superior tests infra, but if and how needs can be discussed later

**Comment by postspectacular** [comment]
Hi @Bnaya - this sounds really good, but let's hold of on this until after the next release cycle. Do I also understand it correctly that switching to jest will require a rewrite of *all* tests and precludes the use of `assert`? This is not a showstopper IMHO, but just would like to know for sure beforehand to better judge amount of effort required...

**Comment by gavinpc-mindgrub** [comment]
Curious what you think @postspectacular about the role of a clojure.spec approach where applicable.  I looked briefly at the available JS ports, and [js.spec](https://www.npmjs.com/package/js.spec) looks the most promising (though stalled for two years).  I imagine you're familiar with spec's value proposition, and although some are more prospective benefits than present ones (such as answering queries about API compatibility), the prospect of information-driven generated tests seems like a more leveraged place to put effort.  For my own stuff, this is the next thing on my list to try out.  Like many other borrowings from Clojureland, it strikes me as "the right answer" for the space it addresses.

Back on earth, I'd also just mention that TS3.7 (released today!) includes significantly more powerful assert capabilities for control-flow analysis.

**Comment by Bnaya** [comment]
jest supports runners for other tools assertions, for example
https://github.com/rogeliog/jest-runner-mocha  

but put jest aside, the mocha + ts-node will take us a long way 

and sure, we will wait with that, actually if we will first do ts3.7, and setup build at composite project for the entire repo, we will benefit even more. we will be able to run tests without building any of the dependent packages

**Comment by postspectacular** [comment]
@gavinpc-mindgrub clojure.spec just arrived when I was slowly leaving Clojure behind, but I've used a somewhat similar (though much less elaborate) approach in the form of [thi.ng/validate](http://thi.ng/validate/). Also, I'm still occasionally revisiting the rough idea of data driven validation which I started in [thi.ng/trio](https://github.com/thi-ng/trio/blob/master/src/entities.org) to define triple-based datastructures (graphs) and validate them... So yes, in general, there's a lot of interesting stuff in that field, but I'm really not up to scratch with the current state & tooling of clojure.spec. From what I gather, there're a lot of proponents, but equally a lot of people who feel that clojure.spec has introduced a level of complexity which didn't exist in clojureland previously and additionally take issue that it's been kind of forced onto the community by clojure core...

If you have a list of interesting clojure.spec projects/use cases I'd like to see them... :)

Ps. you should really join our discord at some point too :)

**Comment by postspectacular** [comment]
@Bnaya I've tried using TS project references in the past, but always failed. Part of the reason why the build became more complicated was the request for supporting multiple output formats, especially UMD. Prior to using `rollup` to create/bundle the CJS & UMD versions, everything was emitted as multi-file CJS, provided a lot less headaches and also allowed more detailed imports (and somewhat smaller resulting bundle sizes of userland projects). Personally, I've no use for UMD,  but have been told it's still important for others (not sure why really, in this day & age). So any steps which can simplify/accelerate building the whole repo would be mucho appreciated!

**Comment by Bnaya** [comment]
I see that as implemented for now :)

**Comment by postspectacular** [comment]
@Bnaya Thank you again & Yeah, I'm sorry I did this in the spur of the moment. First tried it with one of the new packages and it worked great, then quickly applied it across the board. The only issue i had was w/ thi.ng/pointfree-lang, which uses an additional build step (PegJS) to generate its parser, so that one I left at the old setup...

As for your `jest` comment, let's deal with this separately, since this is potentially going to be a hefty effort and I really can't prioritize this in the near future (already spending too much of my little time on refactoring the docs). Is jest really going to make testing that much easier? I know close to nothing about it, but always happy to take advice from those in the know :)

**Comment by gavinpc-mindgrub** [comment]
Have been super busy myself @postspectacular but just wanted to chime in with unwavering support for UMD.  I could not use this project without it (and it was very encouraging to see UMD support added almost immediately after I found it).  I don't use Webpack & co, and I don't see them as solution to modules but rather a reframing of the whole system around themselves in order (in part) to avoid having an actual module loader, which AMD/require is.  AMD loaders are really simple to implement, and they reflect the reality that modules are functions of their dependencies.  They are a userland solution to a userland problem, and as such are tremendously flexible to do interesting things with.

Okay, I know this isn't about tests, and yes, I'll stop hijacking other people's tickets!  (But also thanks for the riff on spec... I appreciate that context & will follow up appropriately.)
