### ISSUE TITLE
build: add linebreak config to .gitattributes

### ISSUE THREAD

**Issue by postspectacular** [thi-ng/umbrella#160]
For the sake of avoiding Windows style CRLF line endings, we should add a repo wide config to `.gitattributes` and `.prettierrc` as per:

https://github.com/thi-ng/umbrella/commit/12e445ac27960d3498d8b57ed6daa1520a60158e#commitcomment-35815425

**Comment by loganpowell** [comment]
Looking forward to clean diffs in the future!
