### ISSUE TITLE
[rstream-log] Unable to build a Typescript project while using rstream-log

### ISSUE THREAD

**Issue by vidyanand** [thi-ng/umbrella#173]
I am using rstream-log in a Typescript project. When I try to build the project I am getting the following errors ( only pasting two lines from the error here). Other dependent umbrella packages also seem to throw similar errors

```
node_modules/@thi.ng/rstream/from/worker.d.ts:22:55 - error TS2304: Cannot find name 'Blob'.
22 export declare const fromWorker: <T>(worker: string | Blob | Worker, terminate?: boolean, id?: string | undefined) => Stream<T>;

node_modules/@thi.ng/rstream/from/worker.d.ts:22:62 - error TS2304: Cannot find name 'Worker'.
22 export declare const fromWorker: <T>(worker: string | Blob | Worker, terminate?: boolean, id?: string | undefined) => Stream<T>;
```

**Comment by nkint** [comment]
Hi!
Have you tried to add "dom" to my compilerOptions.lib array in tsconfig.json?
Is it a browser or node project?

**Comment by postspectacular** [comment]
@nkint you beat me to it (again!) :) was just double checking it, but that is my hunch too... somehow you must have excluded it...

Also see (`lib` section & defaults):
https://www.typescriptlang.org/docs/handbook/compiler-options.html

**Comment by vidyanand** [comment]
Thanks. I just did that and it helped. However I am running into the following now:

```
node_modules/@thi.ng/transducers/iter/as-iterable.d.ts:6:58 - error TS2315: Type 'Generator' is not generic.
6 export declare function asIterable<T>(src: Iterable<T>): Generator<T, void, undefined>;

node_modules/@thi.ng/transducers/iter/choices.d.ts:17:131 - error TS2315: Type 'Generator' is not generic.
17 export declare const choices: <T>(choices: ArrayLike<T> & Iterable<T>, weights?: ArrayLike<number> | undefined, rnd?: IRandom) => Generator<any, void, unknown>;
                                                                                                                                     
```

**Comment by postspectacular** [comment]
@vidyanand can you please let me know which version of TS you're using? I haven't tested w/ 3.7 yet and there might be some (new) issues w/ generics

**Comment by vidyanand** [comment]
Thank you @postspectacular . Here is the information you asked for:
> $ tsc --version
> Version 3.7.2

**Comment by vidyanand** [comment]
@postspectacular  - I downgraded typescript to 3.6.3 and can confirm that with version of typescript this seems to be working.

**Comment by postspectacular** [comment]
@vidyanand thanks & that's good to know that there'll be refactoring ahead. Sometimes I wish they (MSFT) wouldn't change the inferencer rules/generics with each new release and break people's code...

**Comment by postspectacular** [comment]
@vidyanand just in case you haven't noticed yet, but end of November, I released new versions of all packages which are now built w/ TS 3.7.2. See new versions here: https://github.com/thi-ng/umbrella#reactive-programming
