### ISSUE TITLE
[hdom-components] ADR-0002 discussion

### ISSUE THREAD

**Issue by postspectacular** [thi-ng/umbrella#18]
Please use this issue to discuss aspects and/or change requests to the component design decisions in [ADR-0002](https://github.com/thi-ng/umbrella/tree/develop/packages/hdom-components/adr/0002-component-configuration.md)

**Comment by vorg** [comment]
Is there any way to implement per component selective updates like in React shouldUpdate?

For complex UIs diffing gets expensive. Example use case:
- small multiples NxN matrix of svg charts (update only on data change)
- filtering ui next to it (update realtime on mouse movement and clicks)

**Comment by postspectacular** [comment]
Hey @vorg - apols for the slow response. It's funny how this question is somewhat related to some stuff I worked on, just this past weekend (i.e. see [this thread](https://twitter.com/thing_umbrella/status/1071593881865764864)...)

Apart from those thi.ng/diff package updates, I uploaded a [small example](https://demo.thi.ng/umbrella/hdom-skip/) of using the still experimental hdom `__skip` control attribute. So far this is just a small experiment, but related work will be happening on the `feature/hdom-skip` branch. It seems to work great in principle, but there's still more to do to actually fail fast any diff operations going on at parent branches...

Source code (with comments) of the demo is here:
https://github.com/thi-ng/umbrella/tree/feature/hdom-skip/examples/hdom-skip

**Comment by postspectacular** [comment]
Earlier today I released a new version of the hdom, hdom-canvas, hiccup, transducers-hdom packages, which all support the new `__skip` attribute to exclude a given element/tree branch from the diff process. The difference to the existing `__diff` attrib is:

- if `__diff: false` - diffing of the branch will be skipped and the new branch simply replaces the old one entirely
- if `__skip: true` - diffing of the branch will be skipped and no other action is being taken

For that reason, `__skip` should **never** be enabled when a component is first introduced to the tree (i.e. in it's first frame), since this will upset future diffs and will cause undefined behavior.

There're some more comments in the [doc string](https://github.com/thi-ng/umbrella/tree/master/packages/hdom#__skip). Also check out the [new benchmark](https://demo.thi.ng/umbrella/hdom-benchmark2/), which still gives me a stable 60fps for a 64x64 grid with 128 random cell updates per frame (i.e. ~310 DOM updates in a DOM w/ 4200 nodes in total). I'd say this is plenty enough...
