### ISSUE TITLE
[all] README usage example links are broken

### ISSUE THREAD

**Issue by acarabott** [thi-ng/umbrella#185]
The usage example links in the `hdom` package seem to be broken, e.g:

https://github.com/thi-ng/umbrella/tree/master/packages/hdom#minimal-example--1--local-state--raf-update

**Comment by postspectacular** [comment]
Ahh, thanks... I know why that is. There's some discrepancy between GH's href encoding and the one used by [the new tool to generate all the readme files](https://github.com/thi-ng/umbrella/blob/master/scripts/generate-readme#L198)... seemingly, GH replaces repeated dashes in the anchors with a single dashes.
