### ISSUE TITLE
A thing or two about type safety

### ISSUE THREAD

**Issue by Mateiadrielrafael** [thi-ng/umbrella#191]
Hey, so on the discord server @postspectacular told me about the typesafe versions of paths. I took a look and I was not so happy to see this giant mess (it's actually a lot more but if I make the text even smaller it becomes hard to read):
![this](https://cdn.discordapp.com/attachments/549314199386456114/663334121745022978/unknown.png)

Based on the fact those things are imported from `@thi.ng/api` I'm pretty sure other packages contain code like this as well... But we can do more! Typescript has a pretty neat type system which allows us to write stuff like that without all the repetition!

## Final result:

Before going into more details, here's the final result of the refactor for the code above:
![refactored code](https://media.discordapp.net/attachments/445761258696736790/663338921777823746/unknown.png)

And the good thing is, this works for any path length!

## Building blocks:

To be able to achive that I had to write a few basic types:

> Note: In case you want to see the actual implementations of the types you can take a look at [this typescript playground link](https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=72&pc=1#code/C4TwDgpgBAEhCGATAPAFQHxQLxVVCAHsBAHaIDOUACvAE7wC2Ext5yAFAG4BcUAliQBmEWlABKAGigA6WXQDm5XvBIgA2gF0AlNkwqQ6AFBQTUAPzjjp3iQicRAbkOHQkWAkSoI5YAEZs7kjIar5SAExSAMwa6A5QAPTxUL4u4NBwSF4+YQEZKJqxCUm29rSpbnlZwJG5HsgARCQA9sBQKm209CD1hYlQJSLOrtCo8HwANmiYOHiExGSU+ppWJhbs7LLSCkq4Olh6qjpzpBRQXMqqUpvbvALComJ7ByArpquWb282doNf-T+0JzlEZjcZVfwzUHBUJQCJQaK9JJqOHRYG4UFVHKQibBGJxPrLYboiZVGrYyaNFptEgdLo9fHFAFDNJQADCTRIAGN4MA0FIAKrTah0RjMERsV7nXBXOS0RS8fn4IgnRaqTTmKCK76lJ7Ul6xZludlcnnggLG7m8gAMUhC4SieKKUDUNuS9vhGjRFtN3mAWLZHMtyFdlNa7TodMR-1KhugYgB5Ag8cQAFdOSI+eIpKyhQBvV5W3je3mobMGt6+Xjx0qJ5NpjN5ZBidBSUY45vZwM8zM5g0AXzUYiV81O6osVqgvF8GiBROr4ogUwCs2VC2dGg16qrCaTEFT6doyEbGFbUJP64NaPnrAgZpw18T0PdCIZzsi7unV53mICD8XBSdQkWT-Ulfx3BpmjDGkI3gbpMD6AYyjRAA1eBxj4RAeQgGhgAACzrA9MwAGSkSQoAAeSFIjhxVKAAGsIBAJpBFwV4LHzT5PkLcRwOLZASIo9By040xKygVD0Mw4gcPwvd60PVA1CIjQpEbDtiUmdS+IEyjhLeAch2ONcxygCcp09P5EKBQgwCaWhWiJCSMKwmTiKomjjIs0wLGWP4nKk7CeVk-cM1LQIUCIlsNP4qKClnYDmFoPh7BkgjQuzKRqKM04lhic0PNOBimJY1A2KgDiRJMbjFNZGdXk4sT42AJKUqCtKFLUWrVLqSLTxxSK9NMAcstXUcN3HSdki8kxtUcZwbLshyEua5LArwtyAhGkdKF87zWL+JqWrW4L5MzRteuigagQEFhBHgdMoAAOV9PdyteeBeAqziACNPvqkTORsFMGG+ubKr7Jx9KcPtY1wX0IXEtDnOkoLkGenw91tep4HqKR6m++pHQJbHcfxwm0R-HB-Jc1H0eIRAsZxvHEEJqNENh0D70S1bXLpzG4Z8Xwo1zKBAf6YHQdEGGiSqAAWMCVta9a+YZgW-TZpkgA)

- Head: returns the first element of a tuple:
```ts
type HeadTest1 = Head<[1, 2, 3]>; // 1
type HeadTest2 = Head<[]>; // never
type HeadTest3 = Head<"not an array">; // never
```
- Tail: returns everything except the first element of a tuple:
```ts
type TailTest1 = Tail<[1, 2, 3]>; // [2, 3]
type TailTest2 = Tail<[]>; // []
type TailTest3 = Tail<"not an array">; // never
```
- Concat: Tried adding an item at the start of a tuple:
```ts
type ConcatTest1 = Concat<0, [1, 2, 3]>; // [0, 1, 2, 3]
type ConcatTest2 = Concat<0, "not an array">; // never
```
- Reverse: pretty explanatory name, reverses the order of elements of a tuple:
```ts
type ReverseTest1 = Reverse<[1, 2, 3]>; // [3,2,1]
type ReverseTest2 = Reverse<[]> // []
type ReverseTest3 = Reverse<"not an array"> // never
```

Those are the building blocks for a lot of more complex types. 
___Question 1___: where should I add these? (I'm thinking of `@thi.ng/api` but I'm not sure

## The actual path stuff

Appying the same logic I was able to build a path validator and a path applier which work with any amount of nesting:

```ts
interface Nested {
    a: {
        b: {
            c: number;
        };
    };
}

type Test1 = ValidatePath<Nested, ["a", "b"]>; // ["a","b"]
type Test2 = ValidatePath<Nested, ["a", "d"]>; // never

type Test3 = RetrivePath<Nested, Test1>; // { c: number }
type Test4 = RetrivePath<Nested, Test2>; // never
```

___Question 2___: Does this seem interesting? Should I open a PR making the entire lib use it?

> Note: The paths package was just an example, this could be applied to a lot of other stuff!!!

So, let's discuss it! What do yall think of this method of typing? Should I open PRs with it?

**Comment by Vyctor661** [comment]
Great idea

**Comment by gavinpc-mindgrub** [comment]
Hats off, @Mateiadrielrafael.  Very clever to use function parameters to do tuple operations that are not possible with tuples *per se*.  Whatever the merits of using it for this problem, it's a cool hack.

As the not-so-proud author of some very similar giant messes, I really thought that those overloads were the only way to go.  I use that approach in production on another project and it performs pretty well.  If this performs as well (e.g. on deep types), I'd say that was a clear win.

**Comment by Mateiadrielrafael** [comment]
Hey @gavinpc-mindgrub, thanks a lot!

I've been already working on adding this to `@thi.ng/api` for a while so it should be ready soon

If you want to get your hands dirty with complex types you can read [this cool article which implements numerics with types](https://ostro.ws/2019/12/09/taking-types-too-far/) (This is where I learned most of the hacks from). I think I first saw the tuple operations when I first read [this cool article about compose & pipe](https://dev.to/hemaka/introducing-the-recursive-pipe-and-compose-types-3g9o) ,but those became pretty common so I'm not sure if this is the folk who came up with them.

**Comment by Mateiadrielrafael** [comment]
Opened a pr with the basics! (See #192)

**Comment by postspectacular** [comment]
Hi @Mateiadrielrafael - this is some serious/impressive type wrangling and these would indeed be a great addition for the api package. However, I'd really stress *addition* here since I'm also using those existing `Keys1/2/3...` & `Val1/2/3...` types for other purposes (other than in the paths package) where I need to enforce a specific key length/depth.

As for the "mess" - your approach is of course very flexible & clever, but FWIW all of these existing key/val type versions and function overloads were code generated and in practice I have never ever needed more than 8 levels of hierarchy. It was just a faster (for me to do) and good enough solution for now, but am v. grateful for your contribution and can already see other use cases in the near future.

**Comment by postspectacular** [comment]
@Mateiadrielrafael - oops... you're too fast! :) started writing above reply earlier, will take a look at PR in the morning!

**Comment by Mateiadrielrafael** [comment]
Hey @postspectacular  Never knew it's possible to generate something like that:)

As for other usages of the types: I didn't remove the old ones, just added generalised versions!

**Comment by postspectacular** [comment]
@Mateiadrielrafael - it's not the prettiest code, but as I said earlier, it was the fastest route I could think of so far to achieve the current effect and enable checking for specific lookup path lengths:

```ts
import {
    map,
    range,
    str,
    transduce
} from "@thi.ng/transducers";

const TYPES = "TABCDEFGH";

const generics = (from: number, num: number) =>
    str(", ", TYPES.substr(from, num));

const withSuffix = (name: string, i: number) => (i > 0 ? name + i : name);

const _extends = (name: string, i: number) =>
    i > 1
        ? `${TYPES[i - 1]} extends ${withSuffix(name, i - 2)}<${generics(
              0,
              i - 1
          )}>`
        : "T";

const extGenerics = (name: string, i: number) =>
    transduce(
        map((j) => _extends(name, j)),
        str(", "),
        range(1, i + 2)
    );

const defKey = (i: number) => {
    const name = "Keys";
    const fqn = `${withSuffix(name, i)}<${extGenerics(name, i)}>`;
    const decl = `${withSuffix(name, i - 1)}<T[A]${
        i > 1 ? ", " + generics(2, i - 1) : ""
    }>`;
    return `type ${fqn} = ${decl};`;
};

const defVal = (i: number) => {
    const name = "Val";
    const fqn = `${withSuffix(name, i)}<${extGenerics("Keys", i)}>`;
    const decl = `${withSuffix(name, i - 1)}<${generics(0, i)}>[${TYPES[i]}]`;
    return `type ${fqn} = ${decl};`;
};

console.log(transduce(map(defKey), str("\n"), range(1, TYPES.length)));
console.log(transduce(map(defVal), str("\n"), range(2, TYPES.length)));

// type Keys1<T, A extends Keys<T>> = Keys<T[A]>;
// type Keys2<T, A extends Keys<T>, B extends Keys1<T, A>> = Keys1<T[A], B>;
// type Keys3<T, A extends Keys<T>, B extends Keys1<T, A>, C extends Keys2<T, A, B>> = Keys2<T[A], B, C>;
// type Keys4<T, A extends Keys<T>, B extends Keys1<T, A>, C extends Keys2<T, A, B>, D extends Keys3<T, A, B, C>> = Keys3<T[A], B, C, D>;
...
// type Val2<T, A extends Keys<T>, B extends Keys1<T, A>> = Val1<T, A>[B];
// type Val3<T, A extends Keys<T>, B extends Keys1<T, A>, C extends Keys2<T, A, B>> = Val2<T, A, B>[C];
// type Val4<T, A extends Keys<T>, B extends Keys1<T, A>, C extends Keys2<T, A, B>, D extends Keys3<T, A, B, C>> = Val3<T, A, B, C>[D];
```

Commented on your great PR earlier... thanks again!

**Comment by Mateiadrielrafael** [comment]
I think we can close this
