### ISSUE TITLE
[geom] fitIntoBounds3

### ISSUE THREAD

**Issue by nkint** [thi-ng/umbrella#202]
Hi!
This is a kind of feature request, I'd like to have `fitIntoBounds3` as we have [`fitIntoBounds2`](https://github.com/thi-ng/umbrella/blob/feaf8d3f8c1dd3e9141a151b4e473423a6f62242/packages/geom/src/ops/fit-into-bounds.ts#L34) for 2d `IShape` but for 3d `Vec[]`.

I've tried to implement it by myself and it seems to work well with some 3d random mesh (an icosahedron) but not working for some dumb test points.

Here is the [gist](https://gist.github.com/nkint/101bd30bbb06745dfc1d3d4a23564406). Any help/hint is really appreciated.

**Comment by postspectacular** [comment]
@nkint I've taken your gist and put it in a [codesandbox here](https://codesandbox.io/s/nkint-fit-into-bounds3-cbfcm). Also fixed it and added some comments. The main issue is a division-by-zero case when all input points are planar (i.e. at least one dimension of the source bounding box size is zero). I've added a `safeDiv()` helper fn, which should be added to thi.ng/math and the same fix should also be applied to the existing 2d version... The other comment left in the code is about your result assumption and hope it makes sense...

**Comment by postspectacular** [comment]
Just for future reference: Fixed now and added notes here: https://github.com/thi-ng/umbrella/pull/206#issuecomment-590099786
