### ISSUE TITLE
[Future Suggestion] Use TypeScript Project References

### ISSUE THREAD

**Issue by Bnaya** [thi-ng/umbrella#203]
** I've opened this issue for future reference **

Since 3.0, TypeScript has a feature called Project References
https://www.typescriptlang.org/docs/handbook/project-references.html

That's allow to build multiple related typescript packages with separate tsconfig's using one `tsc --build` command, and more DX improvements 

The main cons is: It uses only one cpu core, and the overall build speed of the entire monorepo will get longer. After some tests on umbrella codebase - it's really meaningful. 
There's an issue for that on TypeScript repo to track that: 
[Support multi-threaded compilation for --build](https://github.com/microsoft/TypeScript/issues/30235)

An intermediate step can a mesh build setup, But i think it's gonna be complicated to configure it correctly

**Comment by postspectacular** [comment]
Hi @Bnaya - could you please share some of your tests with this repo somewhere? I've attempted using project refs twice in the past and always ran into one or more stumbling blocks / unable to build all packages. IIRC one of the main problems is the multi format output via the `bundle-module` script (via `rollup`). Currently, all packages in the repo are configured for TS to emit ES6 modules, which are then transpiled via said script to CJS/UMD formats...

Maybe with a better integration of `ts-node` in my dev workflow (e.g. via additional script aliases in the `package.json` files) the CJS versions aren't needed anymore until it comes to building a release. I've started using it more recently, but I still seem to require additional `tsconfig.json` files to set `"module": "commonjs"` for that purpose...
