### ISSUE TITLE
[matrices] projectV3

### ISSUE THREAD

**Issue by nkint** [thi-ng/umbrella#205]
Hi @postspectacular 👋
So [text-canvas example](https://github.com/thi-ng/umbrella/blob/develop/examples/text-canvas/src/index.ts) is super funny and easy to follow :-) thanks! and I use `matrices.project` (as I told you recently) to have an svg print of my 3d scene and it works great in the end.

But I have to transform all the 3d coordinates in 4d.

I understand it is not really a computational problem but I thought about a `projectV3` version to avoid `add3([0, 0, 0, 1], p, pos)` to add the 4th `w` homogeneous coordinate as always `1`.

At least I can imagine a lot of cases where we want to just plot some 3d scene and we always working with [x, y, z, 1].

Does it make sense?

**Comment by postspectacular** [comment]
@nkint - yeah, good idea & go for it!  It could just be like this (untested):

```ts
export const project3 = (
    out: Vec | null,
    mvp: ReadonlyMat,
    view: ReadonlyMat,
    p: ReadonlyVec
) => (
    !out && (out = []),
    mulV23(out, view, mulV344([], mvp, p))
)
```

Btw. That demo was partially addressed to you, but was going to mention it only once that package is actually ready... 😄 Also, in that example, the `add3([0, 0, 0, 1], p, pos)` is needed because the cube is instanced to 4 different positions, but still, I'm all for a `project3()` :)

**Comment by nkint** [comment]
Super quick test done with [runjs](https://runjs.dev/) is not working, I will double check later:

```
import {
  concat,
  lookAt,
  perspective,
  project,
  rotationX44,
  rotationY44,
  viewport,
  IDENT44,
  mulV23,
  mulV44,
  mulV344
} from "@thi.ng/matrices";
import { add3, setC3 } from "@thi.ng/vectors";

const W = 64;
const H = 32;

const view = lookAt([], [0, 0, 2], [0, 0, 0], [0, 1, 0]);
const proj = perspective([], 60, W / H, 0.1, 10);
const viewp = viewport([], 0, W, H, 0);

const mvp = concat([], proj, view, IDENT44);

console.log("1", project([], mvp, viewp, [23, 42, 5, 1]));

//----------- internals justo to debug in RunJS
const vop = <T extends Function>(dispatch = 0) => {
  const impls = new Array(5);
  let fallback: T;
  const fn = (...args: any[]) => {
    const g = impls[args[dispatch].length] || fallback;
    return g
      ? g(...args)
      : unsupported(`no impl for vec size ${args[dispatch].length}`);
  };
  fn.add = (dim: number, fn: T) => (impls[dim] = fn);
  fn.default = (fn: T) => (fallback = fn);
  fn.impl = (dim: number): T => impls[dim] || fallback;
  // fn.impls = impls;
  return fn;
};
const fromHomogeneous = vop(1);
//----------- internals justo to debug in RunJS

const fromHomogeneous4 = fromHomogeneous.add(4, (out, [x, y, z, w]) =>
  setC3(out || [], x / w, y / w, z / w)
);
const fromHomogeneous4V3 = fromHomogeneous.add(4, (out, [x, y, z, w]) => {
  /*console.log(x, y, z);*/ return setC3(out || [], x, y, z);
});

const projectV3 = (out, mvp, view, p) => (
  !out && (out = []),
  mulV23(out, view, fromHomogeneous4V3(out, mulV344([], mvp, p)))
);

console.log(mulV44([], mvp, [23, 24, 5, 1]));
console.log(mulV344([], mvp, [23, 24, 5]));
console.log("V3", projectV3([], mvp, viewp, [23, 42, 5]));
```

**Comment by postspectacular** [comment]
@nkint - fixed it, the above `project3()` is fine, the issue was the way `w` was wrongly computed in `mulV344()`...

**Comment by postspectacular** [comment]
After https://github.com/thi-ng/umbrella/commit/61c36fcc532d78b21d78dddeee5523155b0798b2, I think we can close this now...
