### ISSUE TITLE
[all] Error with type only exports with TypeScript 3.8.3

### ISSUE THREAD

**Issue by andrew8er** [thi-ng/umbrella#209]
I get a lot of errors like this one with TS 3.8.3, but not with 3.8.2:
```
node_modules/@thi.ng/associative/index.d.ts:1:1 - error TS1383: Only named exports may use 'export type'.

1 export type * from "./api";
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

This is related to this [issue](https://github.com/microsoft/TypeScript/issues/36966) and this [PR](https://github.com/microsoft/TypeScript/pull/37064). It effectively disallows this kind of re-export. I could not find any information, whether this _should_ actually work or not. Anyway, this is a breaking change in Typescript.

**Comment by postspectacular** [comment]
hi @andrew8er - am pretty confused by this, also because we're *not* using namespaces and that linked issue is about `export type * as X` forms. But you're right, it definitely looks like a breaking change and if named exports are only supported now, then we will have to undo those changes again in this repo... 😭 

[Search results](https://github.com/thi-ng/umbrella/search?q=%22export+type+*+from%22&unscoped_q=%22export+type+*+from%22)

**Comment by andrew8er** [comment]
Yeah, it is already used pretty extensively here. I wonder if this is actually intended to work or if this was never supposed to work at all and just slipped in. I hope for the former…

**Comment by postspectacular** [comment]
I just asked for some official clarification in the TS issue, let's see...

**Comment by nkint** [comment]
Hei,
I'm not sure about anything, I'm really confused too, I haven't get deep on how `export type` works exactly and it's not the first time that typescript teams introduced breaking changes.

But... in the last days I have updated few project to the last thi.ng umbrella version (and to the last typescript version) via `yarn upgrade-interactive` and in the first instance everything was full of error about this.

I deleted `node_modules`, reinstalled, restarted vscode and double checked that the vscode ts version is in sync with the workspace version and the error (by clicking in the version number in bottom right of the editor).

**I understand that this advice is ridiculously trivial and silly** but in the end I get error to run away.

I'm not using `@thi.ng/associative` but I'm using other 25 packages of @thi.ng umbrella monorepo so... can you double check @andrew8er ?

The only thing broken right now is prettier that does not support `import type` syntax yet...

Again, sorry if this is not your situation and if this is a silly advice!

**Comment by postspectacular** [comment]
@nkint there seems to have been a change between 3.8.2 and 3.8.3. currently, the umbrella packages use 3.8.2 and i will try this all out tonight w/ the newer version...

FWIW, the `import type` forms can (and already have in some cases) help to reduce package sizes of dependent packages since these kind of imports only exist during compile time and will be elided from the transpiled files... but you'd only use these to import type aliases or interfaces. other constants, enums, classes, functions will have to be imported/exported normally...

**Comment by nkint** [comment]
yes I'm with ts 3.8.3:

```
  ....
  "devDependencies": {
    ...
    "typescript": "^3.8.3"
  },
  "dependencies": {
    "@thi.ng/atom": "^3.1.7",
    "@thi.ng/checks": "^2.5.3",
    "@thi.ng/equiv": "^1.0.15",
    "@thi.ng/geom": "^1.8.2",
    "@thi.ng/geom-accel": "^2.0.4",
    "@thi.ng/geom-hull": "^0.0.35",
    "@thi.ng/geom-isec": "^0.4.4",
    "@thi.ng/geom-poly-utils": "^0.1.33",
    "@thi.ng/geom-resample": "^0.2.15",
  ...
```

**Comment by andrew8er** [comment]
> Again, sorry if this is not your situation and if this is a silly advice!

No problem, sometimes it is good to check again :)

I just tried it again and I am completely sure this error is introduced with TS 3.8.3.

**Comment by nkint** [comment]
Oh! you are right!

I see the same error but only if I open the file `node_modules/@thi.ng/associative/index.d.ts`.

But in my application files... no error.

Screenshot in the application, everything seems to be ok:
![image](https://user-images.githubusercontent.com/609314/76010930-fbb23900-5f13-11ea-99c5-e4474a46d0dc.png)

Also, the tooltip seems to correctly infer the right type...

But the error shows in if I open the `index.d.ts`:
![image](https://user-images.githubusercontent.com/609314/76011346-b6423b80-5f14-11ea-8429-b30d3b170055.png)

🤔

**Comment by postspectacular** [comment]
There's been some update/answer in the other issue:
https://github.com/microsoft/TypeScript/issues/36966#issuecomment-595352403

I will batch update all the `export type` occurrences and do another release asap...

**Comment by postspectacular** [comment]
Oki, people - new versions of all packages are up (also built w/ 3.8.3), which hopefully fixes this (specifically via [this commit](https://github.com/thi-ng/umbrella/commit/94d5ceb6743a2e827c4f70836774f008c4fb6d64)), please do let me know! I've just rebuilt all examples as well and didn't run into any issues...

**Comment by postspectacular** [comment]
Is this working for you now? Can this be closed? :)

**Comment by andrew8er** [comment]
Sorry for the late answer, I was busy during the weekend. I can confirm, this works now 👍 .

**Comment by postspectacular** [comment]
no prob, @andrew8er & thanks, as always, for reporting this! :)

**Comment by postspectacular** [comment]
In case you haven't seen yet - Prettier 2.0.1 has been released over the weekend - yay!
