### ISSUE TITLE
[egf]: alternative #ref syntax

### ISSUE THREAD

**Issue by nichtich** [thi-ng/umbrella#235]
Reasons to change the current `#ref` syntax:

* It mixes a semantical feature (arbitrary tags) with a structural feature (links between nodes)
* It makes impossible a tag named "#ref"
* To much to type for a feature used so frequently in dense graphs
* Not obvious to understand

How about using `->` instead:

~~~
thi:umbrella
    type project
    url https://thi.ng/umbrella
    creator -> toxi

toxi
    type person
    name Karsten Schmidt
    location London
    account -> toxi@twitter
    account -> postspectacular@gh
~~~

**Comment by postspectacular** [comment]
Believe it or not, that was my original design (also having been pre-conditioned by GraphViz syntax of course), but then opted for uniformity in approach (i.e. using the single concept of tags over additional special syntax). Your point re: being a structural feature is very valid, the others I'd consider more minor/subjective though. I will do some more prototyping and report back. Thanks!

**Comment by postspectacular** [comment]
@nichtich just did a quick lunch time refactoring and have updated the parser to use your proposal. Thanks - will check in update later today...
