### ISSUE TITLE
Segmentation: RLE -> Mask

### ISSUE THREAD

**Issue by vkovac2** [thi-ng/umbrella#240]
Hello. I have a problem with loading the mask from RLE. So, I got the json file from labelstudio that had the rle format. I decoded it using the library you mentioned on the example (see the code below).

After decoding and exporting it, I tried loading it in python. The decoded result is of length 22251060, while my image is 2313 x 2405. The shapes do not match, so I cannot make it as a mask.

 Is there some step in between or after that should be done? For your information RLE is of length 363013.

Thanks a lot

Code used for decoding:
readJSON = fs.readFileSync('./3.json', 'utf8')
dataJSON = JSON.parse(readJSON)
completions = dataJSON["completions"]
rle = completions[0]["result"][0]["value"]["rle"]
// unpack
var unpacked = new Uint8Array(decode(rle));
console.log(unpacked.length)

var writeData = JSON.stringify(unpacked);
fs.writeFileSync('myjsonfile.json', writeData, 'utf8');
module.exports = unpacked;

**Comment by vkovac2** [comment]
Forgot to mention, that I used brush label segmentation on LabelStudio

**Comment by postspectacular** [comment]
I'm sorry this wasn't made more clear in the readme, but the RLE format used by this package has nothing to do with the RLE format you're talking about (I know nothing about Label Studio). RLE merely means "Run-Length Encoding" which is a widely used simple form of data compression and there're no real standard formats... Being bit based and using flexible word sizes, this one here is actually one of the more efficient ones, most others merely use a form of `[rle-marker, repeat-count, value-to-repeat,....]`. Hth!

**Comment by postspectacular** [comment]
Ps. For reference: https://en.wikipedia.org/wiki/Run-length_encoding

**Comment by vkovac2** [comment]
Hello @postspectacular, 

Thanks for replying. In the Github repository of label studio they have explicitly mentioned that they used your library's encoding system. I do have an RLE, and I am trying to get an image from it. I used the decode function as mentioned above, however I got much larger dimension than expected. They might have used some kind of custom RLE encoding form. Do you know how can i get the right image?

**Comment by postspectacular** [comment]
Oki - then can you please post some relevant links here (i.e. to labelstudio and the doc/section you saw that reference) so I can take a further look? Thanks! 👍
