### ISSUE TITLE
[hdom] Confused on when component lifecycle functions fire

### ISSUE THREAD

**Issue by jdhollis** [thi-ng/umbrella#244]
I’m a bit confused on when the component lifecycle functions fire.

Based on the documentation, it seemed to me that `init` would only fire when a new element is added to the DOM and `release` would only fire when an element is removed from the DOM. But I think I’m seeing something different in my app. (Granted, this just might be my expectation coming from React.)

When I initially load up the app in the browser, this is the behavior I see (I’m logging key events for visibility):

```
render/canvas:render 1
render/base-layer:render 2
render/base-layer:init 2
render/base-layer:init/add-event-stream 2
state/update!
render/canvas:init 1
render/canvas:init/add-event-stream 1
state/update!
```

Which results in:

```html
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="997" height="971" key="0">
  <g class="canvas" id="canvas-1" transform="translate(498.50 485.50) scale(1.00)" key="0-0">
    <rect fill="#eeeeee" x="-498.50" y="-485.50" width="1994.00" height="1942.00" key="0-0-0"></rect>
  </g>
</svg>
```

So far so good. And the event streams (i.e., `gestureStreams`) make dragging around the canvas and zooming in and out work.

Then I add a node to the database (I’m using DataScript) via the REPL:

```
state/update!
tx-report {…}
```

I have a stream of `tx-reports` from DataScript triggering renders and wired to `updateDOM`:

```clojure
(.subscribe tx-reports
  (.comp txd
    (.trace txd "tx-report")
    (.map txd #(render/app state/ctx state/db))
    (updateDOM)))
```

Which results in:

```
render/canvas:render 1
render/base-layer:render 2
render/node:render 6
render/canvas:release 1
render/base-layer:release 2
render/node:init 6
render/node:init/add-event-stream 6
state/update!
render/canvas:init 1
```

And:

```html
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="997" height="971" key="0">
  <g class="canvas" id="canvas-1" transform="translate(498.50 485.50) scale(1.00)" key="0-0">
    <rect fill="#eeeeee" x="-498.50" y="-485.50" width="1994.00" height="1942.00" key="0-0-0"></rect>
    <g class="node" id="node-6" fill="#000000" transform="translate(0.00 0.00)" key="0-0-1">
      <rect x="0.00" y="0.00" width="150.00" height="150.00" key="0-0-1-0"></rect>
    </g>
  </g>
</svg>
```

I see a few things in the render transcripts that confuse me—

First off, why is the `canvas` component released and initialized again? There have been no direct updates to the element itself—just its children.

Second, why is the `base-layer` component’s `release` getting called? There have been no updates to it either. And, for some reason, it doesn’t seem that it’s `init` is being called again after `release`. I would assume calls to those functions are paired in this situation.

Also, if a component is being released, why does the event handler stick around?

And do element attribute changes result in replacing the element?

This isn’t a show stopper for me yet. I’ve been able to get the behavior I want so far.

I’m just worried about leaking event streams when elements are replaced.

**Comment by postspectacular** [comment]
Hey @jdhollis - thank you for the detailed experience report/question! Would you be able to put the code in a gist or codesandbox somewhere to help me analyse any of these issues? Let me know pls! Thanks!

**Comment by jdhollis** [comment]
I've invited you to the repo. I'll open a separate issue there for discussion.

**Comment by jdhollis** [comment]
Really loving the libraries, by the way. Too bad they're not native ClojureScript ;)

**Comment by postspectacular** [comment]
@jdhollis sorry for delay... am currently on vacation and only part time on here.. will need a few more days, but thanks for invite! 👍

**Comment by jdhollis** [comment]
No rush at all. Enjoy your vacation. Thanks for offering to take a look.

**Comment by jdhollis** [comment]
Running into an issue where `hdom` seems to be duplicating DOM nodes. I suspect it might be related to the callback cycle.

I am triggering a custom event on `init`, but it seems `init` is firing every time I make an update to the node's contents. If I use this custom event to make a state update, it results in duplicate nodes.

**Comment by jdhollis** [comment]
I'm also seeing the `init` on the `.canvas` element firing more than once (which is strange).

**Comment by jdhollis** [comment]
Ok. I think I see what’s causing the issue. (Will have to refactor to validate this theory.)

The way I’ve currently written my functions, I’m creating anonymous functions closing around new data on each render pass. If I’m reading `diff.ts` right, this triggers a full release/init on each pass for every element.

**Comment by jdhollis** [comment]
Ok. Refactor complete, and I've confirmed my theory above. I've had to introduce some additional state accounting to track component constructors by entity id.

Kinda irritating and not particularly idiomatic in Clojure, but at least I understand what's going on. And while I may have to also manually track some of my event handlers, at least I have a path forward.
