### ISSUE TITLE
[system] Allow non ILifecycle objects to be used as a dependency

### ISSUE THREAD

**Issue by allforabit** [thi-ng/umbrella#247]
Please note that this already works but the types are maybe a little strict. See this example:
```
const myFactory = ({dep1, dep2}) => {
  // Combine and use deps here
  // Note I have to cast to ILifecycle here
  return {something: "here"} as ILifecycle;
}

const sys = defSystem({
   item: {
        factory: myFactory,
        deps: [dep1, dep2],
    }
});
```
It doesn't seem to cause much issues when used like this. It just means you don't have to introduce classes for simple dependencies. Although open to the idea that maybe it's not a good idea to include simple object as part of the system :-) I was thinking of things like config objects and the likes.

**Comment by postspectacular** [comment]
@allforabit completely with you & this is something which has been bugging me too, but not sure how to work around it. Currently `defSystem()` only requires [`ILifecycle`](https://github.com/thi-ng/umbrella/blob/develop/packages/system/src/api.ts#L3) instances, which has *both `start()` and `stop()` already declared as optional*, but for some reason TS insists on at least one of them to be present, which I think is actually a bug (in TS) - or counter-intuitive at the very least... Any ideas for a workaround are MUCH appreciated!

**Comment by allforabit** [comment]
Yep I researched this before actually and will try to come up with a PR!

**Comment by allforabit** [comment]
It's down to typescript's weak type detection: https://mariusschulz.com/articles/weak-type-detection-in-typescript#workarounds-for-weak-types

there's a way to type it without doing any casting and keeping typescript happy:
```
interface Config extends ILifecycle {
  url: string;
}

// Will work as 
const configFactory = (): Config => ({ url: "http://thi.ng/" });
```

Alternatively, to disable the weak type detection this could be added:
```
export interface ILifecycle {
    start?(): Promise<boolean>;
    stop?(): Promise<boolean>;
    [prop: string]: any;
}
```

Then any objects can be supplied without inheriting from ILifecycle or anything like that.
