### ISSUE TITLE
Publish *.ts source?

### ISSUE THREAD

**Issue by den1k** [thi-ng/umbrella#25]
(I'm .ts noob)

For any package when using editor (vscode) features such as _jump to source_, it currently opens published, generated `*t.ts` file within the package in `node_modules` because the `*.ts` file does not seem to be published? This means to see the inner workings I must have downloaded the source repo of any library and manually track down the source code. If I'm wrong here I'd appreciate any advice on how to get this to work and apologize for the noise.

https://github.com/Microsoft/TypeScript/issues/12358#issuecomment-261671260

**Comment by postspectacular** [comment]
Publishing only *.js + *.d.ts declarations is indeed the official guidance I've been following so far, but I too have occasionally struggled with the jump-to-source, but don't know how to work around it. Of course, I do have the source repo available, but when I need to check something in 95% of the cases I also just use either the .d.ts or the .js file for reference...
