### ISSUE TITLE
[geom] getPointAtDistance

### ISSUE THREAD

**Issue by nkint** [thi-ng/umbrella#251]
Hi,
I'm going to port the toxiclibs Ray2D/Ray3d `getPointAtDistance` function and I'd like to open a PR but I'm not sure in which package I should put it.

Or maybe there is already a similar function I can't find?

**Comment by postspectacular** [comment]
Hey @nkint - there's a version of it in the geom package here:

https://github.com/thi-ng/umbrella/blob/develop/packages/geom/src/ops/point-at.ts#L48

...but (like all ops in the main geom package) that one requires a shape class instance. Another, more standalone version with just raw `rayOrigin, rayDir, dist` args would maybe be most at home in the vectors package?

**Comment by postspectacular** [comment]
Yay @nkint - just pushed new releases including your PR 🎉 

- @thi.ng/geom@1.13.0
- @thi.ng/vectors@4.7.0
