### ISSUE TITLE
[hdom] state update doesn't trigger rerender (router-basics)

### ISSUE THREAD

**Issue by Korede-TA** [thi-ng/umbrella#253]
hi, i've been building a small webapp using the ["router-basics"](https://github.com/thi-ng/umbrella/tree/develop/examples/router-basics) example app as a template. i've replaced many of the events and converted to using `enum` instead of `const` to represent events and effects, but otherwise i've stuck to the original app structure.

the event that's called to load the initial app state doesn't result in a re-render even though the state atom itself gets updated. routing and the status bar from the template still update fine, so i'm not sure why my custom events don't work.

i'm triggering the initial load event in the homepage component function body:
```ts
/**
 * homepage
 *
 * @param ctx injected context object
 */
export function home(ctx: AppContext) {
    let id = ctx.views.users.deref()![1].id;
    ctx.bus.dispatch(
        ctx.views.users.deref()!.length
            ? [ev.SET_STATUS, [StatusType.SUCCESS, "initial state loaded from cache", true]]
            : [ev.LOAD_INITIAL_STATE, id]);           // <--- dispatching event here

    // -- dereferencing dynamic views here
    let users = ctx.views.users.deref();
    let { lists, activity, tasks } = ctx.views.currentUser.deref();

    return [pageFrame,
      ["main",
          [tile, 'Lists',
            lists.map((m) =>                                   // <-- using dynamic state here
              [list, m.name],
            )],
          [tile, 'Activity', 
            activity.map((n) =>                               // <-- using dynamic state here
              [activityItem, n.title, n.kind], 
         ....
```

the data is being loaded asynchronously so i'm not sure if that's the issue. the pre/post-load event handlers looks something like this:
```ts
    // INITIAL PAGE LOAD
    // loads current user data for summary on 
    [ev.LOAD_INITIAL_STATE]: (_, [__, id]) => ({
        [FX_DISPATCH_ASYNC]: [
          <Event>[
            ev.SET_STATUS,
            [StatusType.INFO, `loading page data...`],
          ],
          <Event>[
            fx.JSON,
            `assets/user-${id}.json`,
            ev.RECEIVE_INITIAL_STATE,
            ev.INITIAL_LOAD_ERROR,
          ],
        ]
    }),
    [ev.RECEIVE_INITIAL_STATE]: (_, [__, json]) => {
        let {messages, ...currentUser} = json;
        return {
            [FX_DISPATCH_NOW]: [
                <Event>[
                  EV_SET_VALUE, 
                  ["currentUser", currentUser]
                ],
                <Event>[
                  EV_SET_VALUE, 
                  [["messages"], messages]
                ],
                <Event>[
                    ev.SET_STATUS,
                    [StatusType.SUCCESS, "Initial state successfully loaded", true],
                ],
            ],
        }
    },

``` 

i also tried to create a Stream from the state Atom, and subscribing `updateDOM` to that but i can't quite figure out how to get that to work.

any tips are greatly appreciated!!

**Comment by Korede-TA** [comment]
this issue might be similar to #244, but i don't have too much context on that one

**Comment by alexlurvey** [comment]
Hi @Korede-TA. When I add your code to the example the LOAD_USER_LIST event has yet to be dispatched. If you're not doing that elsewhere, updating line one of the home function to `let id = ctx.views.users.deref()![1]?.id ?? 1;` would be a quick way to (maybe) see it working. 

I see you have an INITIAL_LOAD_ERROR event. Do you also have this defined in the config to know if you end up in an error state after initial load?
```
        [ev.INITIAL_LOAD_ERROR]: (_, [__, ___]) => ({
            [FX_DISPATCH_NOW]: [
                <Event>[
                    ev.SET_STATUS,
                    [StatusType.ERROR, `error loading initial data...`],
                ],
            ],
        }),
```

**Comment by Korede-TA** [comment]
hey @alexlurvey, thanks for taking a look at this. 

i don't think that's the issue. i have some hard-coded initial state so i'm sure `id` is defined and the `LOAD_INITIAL_STATE` event work. see the dev tools log:
<img width="1192" alt="Screen Shot 2020-09-29 at 9 34 04 AM" src="https://user-images.githubusercontent.com/16245199/94565404-2d377c80-0237-11eb-97e5-81967ac409fe.png">

if i log the `ctx` object after the event has run, i see all the data i'm expecting. just that the DOM isn't being updated to reflect this. the `set-status` event from the example works fine and the status bar get's re-rendered, but the events i've written don't seem to trigger a re-render

**Comment by alexlurvey** [comment]
Discussion from discord chat:

<img width="755" alt="Screen Shot 2020-09-29 at 6 27 05 PM" src="https://user-images.githubusercontent.com/6192716/94626898-b1165680-0281-11eb-87a6-66575b547504.png">
