### ISSUE TITLE
[all] replace enums with type unions

### ISSUE THREAD

**Issue by postspectacular** [thi-ng/umbrella#256]
Various packages in the umbrella repo started out using `const enum`s, which unlike standard `enum`s, would get compiled into numeric constants without any other overhead (i.e. object property lookup). Unfortunately, using `const enum`s would also eventually cause issues with the popular TS `isolatedModules` build flag (see #154) and so most (if not all) of these enums have already been downgraded to normal enums, with not much benefit...

In many cases, the same type safety can be achieved by using type unions of string constants, also potentially providing better (less verbose) development experience.

```ts
enum Type {
  /**
   * Some info about FOO
   */ 
  FOO,
  BAR,
  BAZ
}

// vs
type Type = "foo" | "bar" | "baz";
```

(an alternative/related approach is [shown here](https://github.com/thi-ng/umbrella/issues/154#issuecomment-609056956))

The only potential downside is the loss of docstrings for individual enum values, but that can be addressed at type level... autocomplete and typesafety won't be impacted, though. Would also be good to do some benchmarking before updating the code.

Currently, there're [~30 uses of `enum`s in the repo](https://github.com/thi-ng/umbrella/search?q=%22export+enum%22), not all of them qualify for the above replacement, but many do.

For example, the following examples (not exhaustive) **DO NOT** qualify, since they rely on their specific numeric enum values:

- [IGES Unit](https://github.com/thi-ng/umbrella/blob/dfd8fc6803324d5ff6515478e57af1f7a6b404c4/packages/iges/src/api.ts#L3)
- [IMGUI MouseButton](https://github.com/thi-ng/umbrella/blob/dfd8fc6803324d5ff6515478e57af1f7a6b404c4/packages/imgui/src/api.ts#L34)
- [WebGL constants](https://github.com/thi-ng/umbrella/blob/dfd8fc6803324d5ff6515478e57af1f7a6b404c4/packages/webgl/src/api/stencil.ts#L3)

**Comment by nkint** [comment]
I am a big supporter of string versus enum, so.. 🎉
