### ISSUE TITLE
[dsp] FFT normalization and Power calculations are inconsistent.

### ISSUE THREAD

**Issue by rkesters** [thi-ng/umbrella#258]
The `normalizeFFT` function scales by a factor if `1 / Math.sqrt(complex[0].length)`, I am unaware of why you would normalize an FFT in this manner. Instead I expected the factor to be `2/N`, where N = number of samples, see `sf` below.

Additionally, the  `spectrumPow`, scales the power by `1/N`. I find it odd any scaling is applied, but if a scale is applied it should be applied to the bin value, `const p = (1/N * real[i]) ** 2 + (1/N * img[i]) ** 2;` . Unless you are scaling again by `1 / Math.sqrt(complex[0].length)`, which I don't understand.

```typescript
import {
	osc,
	fft,
	spectrumMag,
	normalizeFFT,
	spectrumPow,
	scaleFFT,
} from '@thi.ng/dsp';
import { NumericArray, TypedArray } from '@thi.ng/api/api/typedarray';
import { TAU } from '@thi.ng/math';

function cos(phase: any, freq: any, amp: number = 1, dc: number = 0): number {
	return dc + amp * Math.cos(phase * freq * TAU + Math.PI / 6);
}

function main() {
	const FS = 512;
	const o = osc(cos, 10 / FS, 0.5);
	const d = o.take(FS);
	const ff = fft(d);
	const nf = normalizeFFT([[...ff[0]], [...ff[1]]]);
	const sf = scaleFFT([[...ff[0]], [...ff[1]]], 2 / d.length);
	const M: NumericArray = spectrumMag(ff);
	const nM: NumericArray = spectrumMag(nf);
	const sM: NumericArray = spectrumMag(sf);
	const bin = FS / d.length;
	const index = 10 / bin;
	console.log(`FFT magnitude @ 10Hz:\t\t\t${M[index]}`);
	console.log(`normalized FFT magnitude @ 10Hz:\t\t${nM[index]}`);
	console.log(`scaled FFT magnitude @ 10Hz:\t\t${sM[index]}`);

	const pow = spectrumPow(ff);
	const npow = spectrumPow(nf);
	const spow = spectrumPow(sf);
	console.log('------------------------------');
	console.log(`FFT power @ 10Hz:\t\t\t${pow[index]}`);
	console.log(`normalized FFT power @ 10Hz:\t\t${npow[index]}`);
	console.log(`scaled FFT power @ 10Hz:\t\t${spow[index]}`);
}

main();
```

The output of the above:

```
FFT magnitude @ 10Hz:                     128
normalized FFT magnitude @ 10Hz:   5.656854249492381
scaled FFT magnitude @ 10Hz:         0.5
------------------------------
FFT power @ 10Hz:                           32
normalized FFT power @ 10Hz:       0.0625
scaled FFT power @ 10Hz:               0.00048828125
```
The power should be be the square of the magnitude, the above shows that it's not.   

Recommend changes:

For spectrumPow: remove scale for the function,
For normalizeFFT: Add arg named N and scale by 2/N.  default N = complex[0].length. The reason for the `2` is that this is a one-sided FFT, hence we need to double it. 

With these changes:
```
FFT magnitude @ 10Hz:                      128
normalized FFT magnitude @ 10Hz:   0.5
scaled FFT magnitude @ 10Hz:          0.5
------------------------------
FFT power @ 10Hz:                             16384
normalized FFT power @ 10Hz:         0.25
scaled FFT power @ 10Hz:                0.25
```
See, https://www.gaussianwaves.com/2015/11/interpreting-fft-results-obtaining-magnitude-and-phase-information/ , for the FFT of this waveform.

**Comment by postspectacular** [comment]
Hi @rkesters - thank you very much! Please give me a few days to inspect/revisit this code again (since it's quite a long while ago this was written) and also because it was used in a few other projects... will also try your PR and compare more results! 🙏

**Comment by postspectacular** [comment]
I've done *a lot* of re-reading different literature about this topic and can confirm that the current implementation is faulty (but it's too long in the past to figure out where/when the mistaken assumptions were introduced) - however - I've also toyed around with your [PR version](https://github.com/thi-ng/umbrella/pull/259) and found it produces equally confusing, though different results. So back I went to hit the proverbial book shelves and have now updated and added new functions, primarily based on these nuggets:

- https://holometer.fnal.gov/GH_FFT.pdf (probably my fave text on FFT/DFT etc.)
- http://www.it.uom.gr/teaching/linearalgebra/NumericalRecipiesInC/c13-4.pdf (page 550 onwards)
- http://www.hep.ucl.ac.uk/~rjn/saltStuff/fftNormalisation.pdf

I've added the following functions (both time or freq domain):

- `powerSumSquared()`
- `powerMeanSquared()`
- `powerTimeIntegral()`

These additions are helpful to verify Parseval's theorem and for simple aggregation, but specifically the Heinzel report (first link above) made it obvious that one of the fundamental missing aspects of the current normalization and PSD functions is the lack of consideration for any windowing function used (i.e. both the current and your approach just assumed a rectangular window everywhere). Therefore, I've updated `normalizeFFT()`, `denormalizeFFT()` and `spectrumPow()` to support windowing and not just use fixed scale values.

I've also added new tests, gist of it below:

```ts
const FC = 64;
const FS = 512;
const A = 0.5;
const N = 2 * FS;
const I = freqBin(FC, FS, N);

// cosine osc w/ 30 degree phase shift (= 1/12 of circle as normalized value)
const src = osc(cos, add(FC / FS, 1 / 12), A).take(N);

// compute window LUT
const win = window(windowRect, N);

// compute FFT w/ pre-applied window
const fwd = fft(src.slice(), win);

// power functions currently DON'T include window compensation
console.log(
    "powSumSq: src =",
    powerSumSquared(src),
    "fft =",
    powerSumSquared(fwd)
);

console.log(
    "powMeanSq: src =",
    powerMeanSquared(src),
    "fft =",
    powerMeanSquared(fwd)
);

const spMag = spectrumMag(fwd);
const spPow = spectrumPow(fwd, false, N / 2, win);
const spDb = spectrumPow(fwd, true, N / 2, win);

const spPhase = spectrumPhase(thresholdFFT(copyComplex(fwd)));

console.log("mag[I] =", spMag[I]);
console.log("pow[I] =", spPow[I]);
console.log("dB[I] =", spDb[I]);
console.log("phase[I] =", (spPhase[I] * 180) / Math.PI, "deg");

// normalize with window compensation
const norm = normalizeFFT(copyComplex(fwd), win);

const spMagNorm = spectrumMag(norm);

// since `norm` already includes the window weight adjustments
// we use a scale factor of 1.0 here
const spPowNorm = spectrumPow(norm, false, N / 2, 1);

console.log("norm mag[I] =", spMagNorm[I], "pow[I] =", spPowNorm[I]);
```

This results in:

```text
// ✓ parseval's theorem: sum(src[i]^2) = sum(|fft[i]|^2) / N
powSumSq: src = 128.00000000000017 fft = 127.99999999999812
powMeanSq: src = 0.12500000000000017 fft = 0.12499999999999817

// specific bin values
mag[I] = 255.99999999999866
pow[I] = 127.99999999999865
dB[I] = -6.0205999132796695
phase[I] = 29.999999999997627 deg

// using normalized FFT
norm mag[I] = 0.4999999999999974 pow[I] = 0.24999999999999736
```

As you can see, these results make a lot more sense now and I want to thank you pointing out the original error and making me re-read all this stuff 👍 

A single sinusoid at 50% power correctly results in -6 dB (with your PR code it was something like +21 dB?!). 100% power yield 0 dB and 71% (1/sqrt(2)) = -3 dB...

I'd still like to update the `powerXXX` functions to take windowing into account, but I'm not entirely sure how to do that...

Please also have a look at the various new doc strings...

**Comment by postspectacular** [comment]
@rkesters with regard to the above mentioned updates, can this issue be closed now or still things unclear/buggy for you?

**Comment by rkesters** [comment]
@postspectacular sorry for the delay, yes the changes make since and I close this issue. Thank you for all the work on the issue.
