### ISSUE TITLE
hiccup-css: question about how to use pseudo classes

### ISSUE THREAD

**Issue by sortofsleepy** [thi-ng/umbrella#26]
Hi Karsten 👋 

First off thanks for all the work on these packages! I'm finding them very useful for a lot of things at the moment.

One thing I just ran into though with the hiccup-css package, and perhaps it's an oversight on my part and I simply haven't come across the corresponding code/example,  but is there a way to use css pseudo classes with the package? I'd like to set a hover state for something but I don't see an obvious way to do so. 

Thanks!

**Comment by sortofsleepy** [comment]
Gagh! Apologies. it's still too early - forget I asked, I didn't think of just writing out the pseudo class directly when writing the selector. I've used SCSS for too long  and was so used to writing out
```scss
h1{
  &:hover {}
}
```
It's slightly less ideal writing it out with the selector but I can make this work. 

Thanks again!

**Comment by postspectacular** [comment]
Hi @sortofsleepy - firstly, thank **you** for the kind words & trying out the libs! 😄 

I always thought I did document the use of pseudo-classes, but it's seems I didn't and it something I'll correct asap. For now please take a look at overall pattern in this test case here:

https://github.com/thi-ng/umbrella/blob/master/packages/hiccup-css/test/index.ts#L36

Pls let me know if this works for you!

**Comment by sortofsleepy** [comment]
@postspectacular 

Ah ha! Yup, that worked. 

I had essentially tried the code described in the test but for some reason it hadn't occurred to me to try square brackets and I was using curly braces instead. doh!

Thanks so much again!

**Comment by postspectacular** [comment]
Square brackets are used to delineate nesting levels, curly ones are **always** just used for attributes/properties...

Also, reopening this issue for my own purposes (as reminder to update readme)...

**Comment by sortofsleepy** [comment]
Gotcha, I'll keep that in mind. (and apologies for closing too early)
