### ISSUE TITLE
[geom-isec] rayBox intersection code is incorrect?

### ISSUE THREAD

**Issue by Jarred-Sumner** [thi-ng/umbrella#269]
I was looking at how to do a 3D ray box intersection test, and I found this function:
https://github.com/thi-ng/umbrella/blob/758dff6137388bb8a3a1a26a877e081383ca4dcd/packages/geom-isec/src/ray-rect.ts#L45-L63

I noticed that it reassigns the values of `t1` and `t2` without assigning `tmax` and `tmin` for the Y axis. 

On line 54, I think it's missing:
```ts
tmin = min(t1, t2, tmin)
tmax = max(t1, t2, tmax)
```

Also, `Math.min` and `Math.max` supports multiple arguments. From a quick benchmark in Chrome devtools, its about 12% faster to pass multiple arguments instead of one per call.
![image](https://user-images.githubusercontent.com/709451/103162138-58cbf380-47a1-11eb-8c45-0d0fa2c67d3b.png)

**Comment by postspectacular** [comment]
Thanks for spotting this @Jarred-Sumner! 👍  The issue likely seems to have been some copy & paste mistake, at least partially:

https://github.com/thi-ng/umbrella/commit/441cddbdc4707465a182f3fa903a4c6bdc4e9004#diff-4077e9cb74961b66ba8c27be15e542a7c959d479e30b19bdbeac3b51558e5233R56

The Z-axis min/max handling is part of the return statement, but the (former) lines 60-61 needed to be moved to 56-57 to correctly clamp the Y-axis results. I'm not quite sure why you refer to re: the multi-arg `Math.min` calls - each axis' results are successively combined via a mixed min/max form, so the 3+ args form doesn't really apply here... can you explain more please?
