### ISSUE TITLE
[hdom] use rAF render loop only on state changes

### ISSUE THREAD

**Issue by den1k** [thi-ng/umbrella#27]
On my machine `start("app", () => ["div", "foo"])` idles at 5% CPU. It seems diffing happens regardless of state changes. Is there a way to only re-diff after an atom any atom inside has been mutated?

**Comment by postspectacular** [comment]
Yes, it's one of the things which needs more documentation - there're actually several ways to do that and the one I use the most is directly related to having an opinion about state, event & side effect handling in your app:

1) Use @thi.ng/interceptors `EventBus`

[@thi.ng/interceptors](https://github.com/thi-ng/umbrella/tree/master/packages/interceptors) - currently only documented via source code comments, but readme contains links to several related demos (which are heavily commented themselves)

2) Use a watch on the atom / cursor:

```js
import * as hdom from "@thi.ng/hdom";

const domUpdate = (parent, root, state, ctx) => {
  let prev = [];
  state.addWatch("dom-update", (_, __, curr) => {
    curr = hdom.normalizeTree(root(curr, ctx));
    if (curr != null) {
      hdom.diffElement(parent, prev, curr);
      prev = curr;
    }
  });
};

// state atom to watch for updates
const state = new Atom({ ... });
// arbitrary user data
const ctx = {...};
// init DOM update watch
domUpdate(
  // root element
  document.getElementById("app"),
  // root component
  (state) => ["div", ["h1", state.name]],
  // atom or cursor
  state,
  // arbitrary user context
  ctx
);
```

3) Use a derived view

Read up on [derived views](https://github.com/thi-ng/umbrella/blob/master/packages/atom/README.md#derived-views) and use an eager version to drive the DOM update, similar to above. The difference to the watch solution is that views will only re-execute if their value actually has changed. Btw. the empty string arg to `addView()` below refers to the entire parent state's value (atom or cursor). Change it if you just want to attach it to a sub-branch of your state...

```js
const domUpdate = (parent, root, state, ctx) => {
  let prev = [];
  state.addView("", (curr) => {
    curr = hdom.normalizeTree(root(curr, ctx));
    if (curr != null) {
      hdom.diffElement(root, prev, curr);
      prev = curr;
    }
  }, false);
};

// usage as above
```

4) Use @thi.ng/rstream

[@thi.ng/rstream](https://github.com/thi-ng/umbrella/blob/master/packages/rstream), provides a `[fromView()](https://github.com/thi-ng/umbrella/blob/master/packages/rstream/src/from/view.ts) stream of value changes which you can transform using a transducer:

```js
import { Atom } from "@thi.ng/atom";
import { diffElement, normalizeTree } from "@thi.ng/hdom";
import { fromView } from "@thi.ng/rstream";
import { filter, map, scan } from "@thi.ng/transducers";

const state = new Atom({});

const domUpdate = (parent, root, state, ctx) => {
    fromView(state, "").transform(
        // transform view changes using composed transducer (3 stages)
        map((curr) => normalizeTree(root(curr, ctx))),
        filter((curr) => curr != null),
        scan<any, any>([
            () => [],
            (prev) => prev,
            (prev, curr) => {
                console.log("update dom");
                diffElement(parent, prev, curr);
                return curr;
            }])
    );
};

// root component, takes current state & user context
const root = (state, ctx) => ["div", ["h1", ctx.ui.h1, state.name]];

domUpdate(
    document.getElementById("app"),
    root,
    state,
    // arbitrary user context for components
    { ui: { h1: { style: { color: "red" } } } }
);

// triggers DOM update
state.resetIn("name", "den1k");
```

This first & last options are what I'm currently most interested in, especially in conjunction with the [@thi.ng/rstream-graph](https://github.com/thi-ng/umbrella/blob/master/packages/rstream-graph) package to easily declare dataflow graphs...

However, which route to take is very much down to a) complexity of your app and b) statehandling preferences. How to update the UI is IMHO 99% dictated by these 2 factors, but I did not want hdom to be opinionated about this. The included `start()` function is just convenience, but can also be used for these purposes, as e.g. shown in this example:

https://github.com/thi-ng/umbrella/blob/master/examples/router-basics/src/app.ts#L113

**Comment by postspectacular** [comment]
Hey @den1k - I've pushed a complete small example app using the last pattern (4). The code in my prev comment actually has some minor errors WRT hdom user context object handling, but I can only edit later tonight...

Example is here:
https://github.com/thi-ng/umbrella/tree/master/examples/rstream-hdom

**Comment by den1k** [comment]
Thanks @postspectacular! Added a webpack config and index.html and got it to run. Ok so from what I understand, compared to the approach often taken in ClojureScript to diff data (or rather compare pointers) before triggering a vdom-diff, the approaches outlined here, other than 3. derived views, diff the hiccup right away. Is that correct? 

In case you care about the context, I'm looking for the right tools to write a block-based (notebook-like) code editor (similar to notion.so, observablehq, sketch.systems for https://duct.cloud), where all the sub-components of the editor are built from a graph-datastructure (like resolve-map -> rstream-graph) representing the blocks and their dependencies.

**Comment by postspectacular** [comment]
Sorry, @den1k, I forgot to check in those 2 files earlier, fixed now...

You're almost correct with your observation: Though, only option 2 indiscriminately evaluates the hdom root component and then attempts to diff it. Number 4 (`fromView()`) is also based on derived views and hence behaves like 3, but then allows for other stream operators to supplement, instrument, combine or otherwise transform the results (not shown in the demo). Another thing to point out is that, by default, views don't use referential equality but deep equality checking. However, you can customize the equality check when creating a view, e.g. in the `rstream-hdom` demo:

```js
// replace:
fromView(ctx.state, "")
// with:
fromView(ctx.state, "", null, (a, b) => a === b)
```

It might actually make sense to change the default behavior in the future, since any atom value update always creates a new object reference... also [see here](https://github.com/thi-ng/umbrella/blob/master/packages/paths/README.md#structural-sharing)

As for option 1 (using the interceptors `EventBus` for event & state handling): That approach too is selective and will only trigger DOM update if there was any event which triggered a state update as its side effect... I've built a few large apps using this pattern and it worked very well (and efficiently). OTOH I started prototyping a new project setup which combines atom + interceptors + rstream-graph and find it v. elegant, but am not able yet to extract a best practice from these tests.

**Comment by postspectacular** [comment]
@den1k - I've just updated the [rstream-hdom](https://github.com/thi-ng/umbrella/tree/master/examples/rstream-hdom/) demo to **only** use rstream constructs and completely removed the use of atoms for state handling. Maybe you'll find it useful as reference for your project (though am sure there're still more room for refactoring / simplification)...

**Comment by postspectacular** [comment]
@den1k - also do check out the new [crypto-chart](https://github.com/thi-ng/umbrella/tree/master/examples/crypto-chart) demo, which uses the same approach, but is generally a more practical / realworld example...

**Comment by postspectacular** [comment]
@den1k - another update on this: I've added a new package [@thi.ng/transducers-hdom](https://github.com/thi-ng/umbrella/tree/master/packages/transducers-hdom/) to simplify this even more...
