### ISSUE TITLE
Unmet dependency @thi.ng/hex

### ISSUE THREAD

**Issue by nkint** [thi-ng/umbrella#277]
Hi @postspectacular 👋
I have aproject in production where I'm using umbrella.

I just updated a bug fix (not related with umbrella) and after the change the CI pipeline is broken because of the `Unmet dependency @thi.ng/hex`.
This is my `package.json` related to umbrella:

```
    "@thi.ng/compare": "^1.2.2",
    "@thi.ng/geom-isec": "^0.3.10",
    "@thi.ng/geom-poly-utils": "^0.1.40",
    "@thi.ng/math": "^1.7.6",
    "@thi.ng/matrices": "^0.1.11",
    "@thi.ng/transducers": "^5.2.1",
    "@thi.ng/vectors": "^2.4.2",
```

(as you can see are old version)

I did not have time to look at it because it was a one-shot hot fix, my workaround is to add `@thi.ng/hex` as dependency (and everything is working fine), but I suspect there is some minor issue... related to semver maybe?

Nothing serious anyway, just want to point this if anyone has the same problem!

**Comment by postspectacular** [comment]
Ciao @nkint - apologies for the delay! I've just pushed new versions of all packages (incl. various breaking changes, see [table in readme](https://github.com/thi-ng/umbrella#latest-additions--major-updates-2021-02-20)), so please do try again!

I've also been checking (via the [check-imports.ts](https://github.com/thi-ng/umbrella/blob/develop/tools/src/check-imports.ts) tool) all packages and their stated dependencies vs. actual imports used in the source code and the tool didn't find any issues. It might well have been that I missed some in a recent release (similarly and related to #262 I've also added a [check-exports.ts](https://github.com/thi-ng/umbrella/blob/develop/tools/src/check-exports.ts) tool/linter). The thi.ng/hex package is relatively new and was added to dedupe those formatters, so could have missed it as dep in strings or random pkg...

Ps. You might/can also double check dependencies via this new interactive viz: http://dependencies.thi.ng
