### ISSUE TITLE
[rstream] How to keep a stream active when child unsubscribe?

### ISSUE THREAD

**Issue by nkint** [thi-ng/umbrella#282]
Hi @postspectacular, thanks for all the works with rstream! 

Question: how to keep a stream active when childs unsubscribe?

Look at this code:

```js
import {reactive, trace} from '@thi.ng/rstream'

const midiStream = reactive(0, {id: 'midiStream'})

// NOTE: comment the next line line and an illegal state error
const tracedMidiStream = midiStream.subscribe(trace('midiStream'), {id: 'trace-midiStream'})

const subscribtionDumb = {
  next: (event) => { console.log({event}) },
  done: () => { console.log('done') },
}

const s1 = midiStream.subscribe(subscribtionDumb, {id: 's1'})
midiStream.next(1)
// something happens, I want to unsubscribe and re-subscribe
s1.done() // or s1.unsubsribe()
console.log(midiStream.state)
const s2 = midiStream.subscribe(subscribtionDumb, {id: 's2'})
```

If all the children in a stream unsubscribe, the stream state is `UNSUBSCRIBED`. Right know I need to create a dumb subscription (like a `tracedMidiStream` in the snippet above). Is there a better way?

**Comment by gavinpc-mindgrub** [comment]
@nkint, I think `closeOut: CloseMode.NEVER` is what you're looking for.  See ["Common configuration options."](https://github.com/thi-ng/umbrella/tree/develop/packages/rstream#common-configuration-options)

**Comment by nkint** [comment]
ahh, great! thanks!

**Comment by postspectacular** [comment]
Thanks @gavinpc-mindgrub & sorry @nkint if that isn't made obvious/clear enough... Any idea (or PRs) how to make this more prominent in the readme... I feel they all should be restructured somewhat. Will open a new issue to collect ideas...

Also wanted to add, that these same options can be used for any node in the subscription graph, e.g. you can also do this:

```ts
const a = reactive(1);
const b = a.subscribe(trace("b"), { closeOut: CloseMode.NEVER });
const c = b.subscribe(trace("c"));

a.next(1);
// b 1
// c 1

// triggers recursive teardown, but stops at `b` due to CloseMode.NEVER
c.unsubscribe();

// still works
a.next(2)
// b 2
```
