### ISSUE TITLE
Security Issue: Request for contact

### ISSUE THREAD

**Issue by pwntester** [thi-ng/umbrella#285]
Hello,

The [GitHub Security Lab team](https://securitylab.github.com/) has found a potential vulnerability in your project. Please create a [Security Advisory](https://docs.github.com/en/free-pro-team@latest/github/managing-security-vulnerabilities/creating-a-security-advisory) and invite me in to further disclose and discuss the vulnerability details and potential fix. Alternatively, please add a [Security Policy](https://docs.github.com/en/free-pro-team@latest/github/managing-security-vulnerabilities/adding-a-security-policy-to-your-repository) containing a security email address to send the details to.

Kind regards,
A

**Comment by postspectacular** [comment]
Hi @pwntester - thank you for getting in touch - could you at least reveal which package(s) this is about, so I can fill in / prep the advisory form for us to discuss further? Thanks!

**Comment by pwntester** [comment]
Its in [EGF](https://github.com/thi-ng/umbrella/tree/develop/packages/egf)

**Comment by postspectacular** [comment]
Okay, thanks! Meanwhile I've created a draft advisory & added you as collab. Look forward hearing more. Btw. the EGF project is still v. early days and will still undergo major changes (also in terms of file format), but nonetheless keen to learn what you discovered...
