### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by Batarian711** [thi-ng/umbrella#29]
Hi. I am a graphic designer. I volunteer to design a logo for open source projects. I can design it for you to use it in the readme file. What dou you say?

**Comment by postspectacular** [comment]
Hey @Batarian711 - thanks a lot for offering your help, but I don't think there's need or even desire for a logo at this stage. I'm still trying planning how I want to re-structure the thi.ng website and the various libraries (multiple languages, multiple contexts) and these aspects all will have a major impact on the overall identity and its aesthetic. So a standalone logo for umbrella isn't going to be much use in the near future and in fact might actually be a hindrance. Hope you understand!
