### ISSUE TITLE
[webgl] triangle normal?

### ISSUE THREAD

**Issue by nkint** [thi-ng/umbrella#306]
Hi, I'm quite sure it should be there already, but I can't find an method to compute a normal from a 3d triangle...

I will be happy to make a PR to add this, but I'm not sure in which package, maybe it is webgl.geo related? but maybe it is only a geom util?

Moreover I like the idea to add an `out` parameter like all other vector computations but I'm not sure how to handle a `null` case... any ideas?

(just as a note) reference:
- toxiclibs [Triangle3D.computeNormal](https://github.com/postspectacular/toxiclibs/blob/6896bc17e85320e886bdf0819c66491ce484728e/src.core/toxi/geom/Triangle3D.java#L173)
- stackgl/regl [triangle-normal](https://github.com/hughsk/triangle-normal)

**Comment by postspectacular** [comment]
Hi @nkint - what you're looking for is here in the vectors package: 😺 

https://github.com/thi-ng/umbrella/blob/develop/packages/vectors/src/ortho-normal.ts

In the case of `out=null` it writes the result back into `a` (the first point given)...

**Comment by nkint** [comment]
😅😀
