### ISSUE TITLE
[shader-ast-stdlib] Cannot use uniform for octaves in additive fn

### ISSUE THREAD

**Issue by blup** [thi-ng/umbrella#316]
When using `additive("vec2", snoise2, unis.octaves)`, where unis.octaves is "float", I'm getting the error below:
```
Error compiling shader:
line 55: '_sbo' : undeclared identifier
for(float _sbx = 0.0; (_sbx < _sbo); (_sbx++)) {
```

Using it like so `additive("vec2", snoise2, 4)` works, but I need to extract the octaves as a uniform. Is this possible?

Digging into `additive`, i noticed the octaves are fed as an fn argument and not a uniform, I'm wondering if that may be the issue: 
```
export const additive = <T extends Prim>(
    type: T,
    fn: Fn<Term<T>, FloatTerm>,
    oct: number | FloatTerm = 4,
    name = "additive"
) =>
    defn("float", name, [[type], [type], "float"], (pos, shift, decay) => {
        let n: FloatSym;
        let amp: FloatSym;
        return [
            (n = sym(FLOAT0)),
            (amp = sym(FLOAT05)),
            forLoop(
                sym(float(0)),
                (i) => lt(i, float(oct)),

...
```

**Comment by postspectacular** [comment]
Hi @blup - from that error I can't really tell you where it went wrong for you, but in theory you *should* be able to pass in a uniform and you can try it in this Codesandbox here:

https://codesandbox.io/s/shader-ast-snoise-k6cjq

However, the real practical issue (unrelated to shader-ast) is that WebGL v1 does ONLY allow compile-time constants within for-loop iteration tests and will refuse to compile the shader if you do pass a uniform there:

```text
WebGL error : Error compiling shader:
line 54: '_saj' : Loop index cannot be compared with non-constant expression
for(float _saj = 0.0; (_saj < octaves); (_saj++)) {
```

If you do require this to be dynamic, then IMHO using WebGL 2 is the only viable way - or in WebGL 1 - re-compiling/regenerating the shader with new settings...

**Comment by blup** [comment]
Thanks for taking the time to make an example! I am using a WebGL2 context like so `const gl = canvas.getContext("webgl2")`, but I must be doing something else wrong. I'll close the issue since it clearly works in your example.

**Comment by postspectacular** [comment]
@blurp no prob - that example was just a quick mash up of these two:

- https://github.com/thi-ng/umbrella/tree/develop/examples/shader-ast-noise
- https://github.com/thi-ng/umbrella/tree/develop/examples/webgl-shadertoy

If you still are stuck (and want some more help), maybe you could upload a gist/sandbox/codepen yourself? Would be interesting to find out where things go wrong, also to help others in the future...

**Comment by blup** [comment]
I ended up resolving it, but I'm unsure what the problem was. I simplified my shader so all the code was within `defMain` (unis.octave was being passed to a `defn`) and it started working. I may have also been missing a `sym()` here and there - I couldn't find docs for it at the time but eventually figured it out from the context. Here's the working shader for reference, though it's not too different from your examples:
```
    model.shader = defShader(gl, {
      vs: (gl, _, attribs) => [
        defMain(() => [assign(gl.gl_Position, vec4(attribs.position, 0, 1))]),
      ],
      fs: (gl, unis, _, outs) => [
        defMain(() => [
          (uv = sym(aspectCorrectedUV($xy(gl.gl_FragCoord), unis.resolution))),
          (col = sym(
            additive("vec2", snoise2, unis.octaves)(
              add(uv, unis.time),
              vec2(unis.shift),
              float(unis.decay)
            )
          )),
          assign(outs.fragColor, vec4(vec3(fit1101(col)), 1)),
        ]),
      ],
      attribs: {
        position: "vec2",
      },
      uniforms: {
        resolution: ["vec2", [size, size]],
        time: "float",
        octaves: "float",
        shift: "float",
        decay: "float",
      },
    });
```

**Comment by postspectacular** [comment]
Apols for the lack of documentation, `sym()` is used to define a (local) variable/symbol in the syntax tree. This might initially feel somewhat strange, since we're usually also assigning the result of `sym()` to a variable in TypeScript/JS, but what the latter actually contains is just a _symbolic_ reference to that target variable in the form of a AST node, e.g.

```ts
sym(vec2(1))
// {
//   "tag": "sym",
//   "type": "vec2",
//   "id": "_s4",
//   "opts": {},
//   "init": {
//     "tag": "lit",
//     "type": "vec2",
//     "info": "n",
//     "val": [
//       {
//         "tag": "lit",
//         "type": "float",
//         "val": 1
//       }
//     ]
//   }
// }
```

Uniforms passed to the main shader function are also just such symbols, albeit with different qualifiers/options:

```ts
uniform("float", "octaves")
// {
//   "tag": "sym",
//   "type": "float",
//   "id": "octaves",
//   "opts": {
//     "q": "in",
//     "type": "uni"
//   }
// }
```

I will do some further digging if I can see why you would run into an error when passing uniforms as arguments to a function. Checking in the Node REPL, it all seems dandy:

```ts
> ast=await import("@thi.ng/shader-ast")
> glsl=await import("@thi.ng/shader-ast-glsl")

> octaves = ast.uniform("float", "octaves")
// {
//   tag: 'sym',
//   type: 'float',
//   id: 'octaves',
//   opts: { q: 'in', type: 'uni' },
//   init: undefined
// }

// dummy function to call from main
> fn = ast.defn("float", "foo", ["float"], (x) => [ast.ret(x)]);
// [Function: $] {
//   tag: 'fn',
//   type: 'float',
//   id: 'foo',
//   args: [ { tag: 'arg', type: 'float', id: '_s5', opts: [Object] } ],
//   deps: [],
//   scope: { tag: 'scope', type: 'void', body: [ [Object] ], global: false }
// }

> prog = ast.program([octaves, ast.defMain(() => [fn(octaves)])]);

// transpile to GLSL
> console.log(glsl.targetGLSL()(prog))
// #version 300 es
// uniform float octaves;
// float foo(in float _s5) {
// return _s5;
// }
// void main() {
// foo(octaves);
// }
```
