### ISSUE TITLE
[geom-resample] error related to strings

### ISSUE THREAD

**Issue by HarelM** [thi-ng/umbrella#318]
I'm not sure what changed in my environment as this used to work, but lately I'm getting error message when trying to build my project:
```
./node_modules/@thi.ng/vectors/string.js:3:0-57 - Error: Module not found: Error: Can't resolve '@thi.ng/strings' in '/Users/harel/IHM/Site/IsraelHiking.Web/node_modules/@thi.ng/vectors'

Error: node_modules/@thi.ng/vectors/string.d.ts:1:26 - error TS2307: Cannot find module '@thi.ng/strings' or its corresponding type declarations.

1 import { Stringer } from "@thi.ng/strings";
```

Might be because this is not marked as a dependency of geom-resample?
I'm not sure what changed in my env, probably the fact that I cleaned the npm chace, upgraded to 7, downgraded back to 6 and recreated the package lock which might have updated some packages... I guess...

As a workaround I added strings to my package.json and it solved the problem, but I would like to avoid it if possible...

**Comment by postspectacular** [comment]
Yes, sorry this was indeed a missing dependency in the thi.ng/vectors package, but [already fixed](https://github.com/thi-ng/umbrella/commit/e1cf29ebcf2c083285fd017010180282cba221dd#diff-c0290e69fcdd8ec8c36d85d1800849e904b18ab6d9068f7b993d709913535e31). New releases of **all** packages coming in next few days...

**Comment by HarelM** [comment]
Thanks!!

**Comment by HarelM** [comment]
Any updates on this?
