### ISSUE TITLE
[all] Usage in beta.observablehq.com?

### ISSUE THREAD

**Issue by postspectacular** [thi-ng/umbrella#33]
Discussion based on this [tweet by @den1k](https://twitter.com/denik/status/1024861822950752256):

> do you think umbrella would play well in https://beta.observablehq.com/ ? since it has a reactive (but I think promise based) update model straightforward interpolation of HTML / svg, e.g. html`<span>foo</span>`

**Comment by den1k** [comment]
I'm simultaneously exploring umbrella, observablehq and getting back into javascript, where many es6 features are still opaque to me. Here's why I'm curious to combine umbrella and observable:

- [hiccup/hiccup-svg/hdom] it's possible but not common to use react on observable. most html is built stringing HTML strings together by hand. maybe hdom could capture some attention there [experiment](https://beta.observablehq.com/@den1k/thi-ng-umbrella-https-github-com-thi-ng-umbrella)
  - I couldn't get updates to work yet
- observable's reactive bindings to vars and umbrella's various data display / viz abilities seem like a great fit. only caveat, I couldn't figure out how to get observable to update when not the entire value of the var is reset but only, say, a key on an object.

I'd love to see a small HTML app using hiccup with resolve-map or hdom / rstream is necessary.

**Comment by postspectacular** [comment]
Thanks @den1k for this initial example. Until tonight, I'd not yet used Observable myself, but your example really helped me to get started and I've created a little [notebook](https://beta.observablehq.com/@postspectacular/thi-ng-umbrella-https-github-com-thi-ng-umbrella-observable) based on your attempt.

I still have yet to figure how to actually do DOM diffing in their setup, but this might not be possible until we know how to get a handle on the actual DOM element. At the moment, I can only recreate the DOM completely using `hdom.createDOM()`, but it'd be nice to figure out how to get a cell's DOM element directly. Once we know, we should then be able to just use the `transducers-hdom` package to plug in the reactive/on-demand UI diffing.

**Comment by postspectacular** [comment]
I cracked it: The trick was to define a cell which just pre-creates a blank DOM element and then use this cell's value for the `updateUI()` transducer. I've created [another fork of that notebook](https://beta.observablehq.com/@postspectacular/thi-ng-umbrella-https-github-com-thi-ng-umbrella-observable/2) and added more comments there...

**Comment by postspectacular** [comment]
Just added a more minimal scaffolding notebook: https://beta.observablehq.com/@postspectacular/thi-ng-umbrella-scaffold

**Comment by mbostock** [comment]
Here’s another approach to diffing using `this` (the previous value returned by a cell):

```js
{
  const tree = hdom.normalizeTree(root);
  const element = this ? (hdom.diffElement(this.parentNode, this._tree, tree), this) : hdom.createDOM(null, tree);
  element._tree = tree;
  return element;
}
```

Or, as a reusable function:

```js
function hdomify(element, root) {
  const tree = hdom.normalizeTree(root);
  if (element) hdom.diffElement(element.parentNode, element._tree, tree);
  else element = hdom.createDOM(null, tree);
  element._tree = tree;
  return element;
}
```

And then to use:

```js
hdomify(this, root)
```

**Comment by postspectacular** [comment]
Nice one & thank, @mbostock! - `this` was too trivial for me to consider :) Will update the notebook later today...

**Comment by postspectacular** [comment]
Yeah, I don't know how to get this work either, but am sure it's possible. Need to study @jashkenas' input widgets. Anyhow, forked your latest and made some interim updates:

https://beta.observablehq.com/d/4589669c6171caa8

**Comment by postspectacular** [comment]
Okay, one hack later and I've got a version which kinda works (incl. undo/redo history of user interactions). Didn't fork, just updated the same notebook:

https://beta.observablehq.com/@postspectacular/thi-ng-umbrella-scaffold-w-hdom-context

**Comment by den1k** [comment]
nice hack @postspectacular
