### ISSUE TITLE
[transducers] feature async generators

### ISSUE THREAD

**Issue by ja0nz** [thi-ng/umbrella#333]
As a big fan of **async generators** I would love to see some support from the @thi.ng/transducers package. 
Conceptually they are not too far from normal iterators anyway so I hope this feature is possible.
|                          | Iterators       | Async iterators      |
|-----------------------------------|-----------------|----------------------|
| Object method to provide iterator | Symbol.iterator | Symbol.asyncIterator |
| next() return value is            | any value       | Promise              |
| to loop, use                      | for..of         | for await..of        |

### Example usage: NodeJS - simple directory recursion
``` javascript
import { opendir } from "node:fs/promises";
import { extname, join } from "node:path";

async function* walk(dir) {
  for await (const d of await opendir(dir)) {
    const entry = join(dir, d.name);
    if (d.isDirectory()) yield* walk(entry);
    else if (d.isFile()) yield entry;
  }
}

const collectMarkdownFiles = await transduce(filter(p => extname(p) === ".md"), push(), walk('.'))

```
### Example usage: Alternating URL fetch
``` javascript
async function* getResources() {
  yield fetch('https://someurl.org')
  yield fetch('https://someFallback.org')
}

// Imperative usage
for await (const res of getResources()) {
  if (res.status === 404) continue;
  // response handling
  break;
}

// Declarative usage
const payload = await transduce(/* response handling */, push(), getResources())
```

**Comment by postspectacular** [comment]
Just a quick one: There's a 3.5 year old branch for async transducers. I stopped with it due to widespread lack of async/await support back then. I've been meaning to revisit it for a while, just no bandwidth so far. If you're interested in taking a peek:

https://github.com/thi-ng/umbrella/blob/feature/async-transducers/packages/async/src/index.ts

**Comment by postspectacular** [comment]
Closing this since there's a thi.ng/transducers-async package for a few months now...
