### ISSUE TITLE
[ramp] sort is not stable when time indexes are equal

### ISSUE THREAD

**Issue by odbol** [thi-ng/umbrella#343]
```
const stops = [
  [0, 1],
  [1, 4],
  [1, 3],
  [2, 1]
];

const ramp = new HermiteRamp([...stops]); 

ramp.sort();
assertEquals(stops, ramp.stops);
```

Instead, ramp.stops swaps [1, 4] and [1, 3], because it is using comparator2. It should not be sorting by the y values, only the x (time) index.

**Comment by postspectacular** [comment]
Just merged your PR, thank you! Can't tell you anymore, why on earth I used `comparator2()` for sorting, might have been some experiment which sneaked/remained in somehow...
