### ISSUE TITLE
[matrices] Identity function returns the wrong argument

### ISSUE THREAD

**Issue by JakeCoxon** [thi-ng/umbrella#352]
Identity and the `set` function seem to return a different argument to the `out` vec. Presumably not indented

Reproduce:
```js
const m = identity44([]);  // Returns the frozen identity
m[0] = 1000 // Has no affect
console.log(m[0]) // 1
```

Looks like https://github.com/thi-ng/umbrella/blob/develop/packages/matrices/src/set.ts#L6 calls compile with default arg which is 'a' https://github.com/thi-ng/umbrella/blob/develop/packages/vectors/src/compile/emit.ts#L165 but all other functions that use `vector` set return the `o` argument https://github.com/thi-ng/umbrella/blob/develop/packages/vectors/src/set.ts#L9

**Comment by postspectacular** [comment]
Thank you for reporting this! Just fixed it & will release later tonight...

**Comment by postspectacular** [comment]
Oki, the fix is published now:

https://github.com/thi-ng/umbrella/blob/develop/packages/matrices/CHANGELOG.md#2122-2022-08-16
