### ISSUE TITLE
[hiccup] error: x.toHiccup is not a function when drawing hiccup shapes

### ISSUE THREAD

**Issue by Jonaskouwenhoven** [thi-ng/umbrella#353]
I have created a couple of shapes as specified in [here](https://github.com/thi-ng/umbrella/tree/develop/packages/hiccup-canvas#supported-shape-types) , when I print them to the console they have the following structure:
<img width="570" alt="Screenshot 2022-08-22 at 17 43 41" src="https://user-images.githubusercontent.com/33288237/185974689-c1e4352d-c775-40a2-8d86-828039ee8d52.png">
But when I try to draw them to the canvas with the Hiccup draw functions, I get the error that `x.toHiccup is not a function when drawing hiccup shapes`. Is there something i'am missing?

**Comment by postspectacular** [comment]
Hi @Jonaskouwenhoven - could you please upload a minimal example to codesandbox/codepen etc.? Alas, I can't tell what's wrong from what you provided... Thanks!

**Comment by Jonaskouwenhoven** [comment]
Managed to figure it out, thanks for the fast reply!
