### ISSUE TITLE
[all] Request support to run on javascript platforms that don't allow dynamic code

### ISSUE THREAD

**Issue by StringKe** [thi-ng/umbrella#354]
1. https://miniprogram.alipay.com/
2. https://developers.weixin.qq.com/miniprogram/en/dev/

In the above two platforms, they provide a simplified javascript runtime environment. 

including some private javascript runtime environments, the use of javascript capabilities is basically prohibited for security.

1. Executing JS code with `eval` is not supported
1. Creating functions with `new Function` is not supported
    Except new Function('return this')

https://github.com/thi-ng/umbrella/blob/develop/packages/vectors/src/compile/emit.ts#L160
https://github.com/thi-ng/umbrella/blob/develop/packages/pixel/src/convolve.ts#L244
https://github.com/thi-ng/umbrella/blob/develop/packages/pixel/src/internal/codegen.ts#L21
https://github.com/thi-ng/umbrella/blob/develop/packages/shader-ast-js/src/target.ts#L269

There are some codes in the current code repository that use these disallowed features. Are there any plans to support these platforms in the future?

**Comment by postspectacular** [comment]
Sorry, all of the features provided by these listed packages are explicitly relying on code generation and I can't see how one would even work around that in principle. E.g. for the vector & pixel operations there's combinatorial explosion of possibilities and _without_ code generation the number of resulting permutations would be simply unmaintainable and the filesize of these packages would grow exponentially. The shader-ast-js package is designed as an AST-to-JS code generator, so there simply is no alternative static approach at all (other than writing an interpreter, but that's so infeasible as to be pointless, also in performance...)

So I'm sorry to say, but the answer to your question will have to be a strict "no". Hope you understand!

**Comment by StringKe** [comment]
> Sorry, all of the features provided by these listed packages are explicitly relying on code generation and I can't see how one would even work around that in principle. E.g. for the vector & pixel operations there's combinatorial explosion of possibilities and _without_ code generation the number of resulting permutations would be simply unmaintainable and the filesize of these packages would grow exponentially. The shader-ast-js package is designed as an AST-to-JS code generator, so there simply is no alternative static approach at all (other than writing an interpreter, but that's so infeasible as to be pointless, also in performance...)
> 
> So I'm sorry to say, but the answer to your question will have to be a strict "no". Hope you understand!

OK, thanks.

I guess this is the reason why code generation is used.

I didn't think of any other way, so wanted to ask the repository contributors if there is a similar solution.
