### ISSUE TITLE
[wasm-api-dom] allow storing a anyopaque pointer with EventListener

### ISSUE THREAD

**Issue by MarcusWagberg** [thi-ng/umbrella#355]
I've been playing around with the wasm-api-dom package, and the current implementation of EventListener seems to work when using global state. However there doesn't seem to be an easy way to deal with instantiated state.

To me the simplest idea for how to solve this seems to be, make EventListener a struct of the function pointer and an optional anyopaque pointer. Then make dom_callListener call the function with the optional anyopaque pointer.

Somthing like this:
```zig
pub const EventListener = struct {
    callback: *const fn (event: *const dom.Event, data: ?*anyopaque) void,
    data: ?*anyopaque,
};

export fn dom_callListener(listenerID: usize, event: *const dom.Event) void {
    if (eventListeners.items[listenerID]) |listener| listener.callback(event, listener.data);
}
```

**Comment by postspectacular** [comment]
Yes, that's exactly what I was planning to do (same pattern as you'd also do in C aka supplying an additional `*void` arg for arbitrary user context). The only reason why this isn't the case yet is lack of time, but happy to accept a PR! *wink wink* :)

**Comment by postspectacular** [comment]
Also @MarcusWagberg - if you happen to be at the SYCL/Zig meetup in Milano this weekend, it'd be great to chat about some other ideas with you...

**Comment by MarcusWagberg** [comment]
@postspectacular unfortunately i won't be at SYCL, but a PR is incoming.

**Comment by postspectacular** [comment]
Hi @MarcusWagberg - have just added some more updates to the Zig listener handling. Added a new `FreeList` wrapper with implicit storage of free slots to avoid linear search when adding new listeners. More comments in commit: https://github.com/thi-ng/umbrella/commit/e2a63c2b097913925b58448c1e41478def5ff468
