### ISSUE TITLE
[color-palettes] broken links in README.md

### ISSUE THREAD

**Issue by matasaru** [thi-ng/umbrella#394]
The links for proximityLCH() and proximityRGB() functions in the README.md return 403 status. The other links work fine.

<img width="1253" alt="Screenshot 2023-04-07 at 13 10 21" src="https://user-images.githubusercontent.com/1546100/230649505-459bfeee-dcca-411f-9c2f-188d4c94c892.png">
<img width="1253" alt="Screenshot 2023-04-07 at 13 10 29" src="https://user-images.githubusercontent.com/1546100/230649516-a22ff2a4-be98-40c8-af49-b9a3de3341d5.png">

**Comment by postspectacular** [comment]
Thank you for reporting this @matasaru - I released an update with the fix earlier today!

**Comment by matasaru** [comment]
Thank you for the amazingly spectacular thi.ng(s) you put out!
