### ISSUE TITLE
[@th.ing/transducer] weird behaviour when combining `mapcat` with `multiplex`

### ISSUE THREAD

**Issue by tien** [thi-ng/umbrella#401]
```ts
const transducer = tx.multiplex(
  tx.comp(tx.mapcat((x) => x)),
  tx.map((x) => x)
);

tx.transduce(transducer, tx.push(), [[1, 2], [3]])

const expect = [[[1, 2], [1, 2]], [[3], [3]]]
const actual = [[[1, 2], [1, 2]], [3, [3]]] // array of size 1 got unexpectedly flattened

// Also TS definition can possibly improved
type ExpectType = [number[], number[]]
type ActualType = [number, number[]]
```

**Comment by postspectacular** [comment]
Thank you - for `multiplex()` this is indeed unexpected behavior, but it's actually down to the expected & documented behavior of [`step()`](https://github.com/thi-ng/umbrella/blob/07e884f38fe9baa46f48101943ede6c439d1e76d/packages/transducers/src/step.ts#L52) which is being used internally. To fix this for `multiplex()`, I think it's best to add a custom version of this stepper which doesn't have this special case handling (unwrapping) for single-value results. Will work on this today and release with next cycle...

**Comment by tien** [comment]
Awesome, thanks for the quick response 💪

This lib is a god send btw 🙏

**Comment by postspectacular** [comment]
We could check if the result of a single item array with the item an array itself, but that's too fragile and will have a ton of edge cases. The only sure fire way would be to update the `multiplex()` args and allow disabling the current unwrap behavior (per given transducer), something like this:

```ts
multiplex(
  // provide as tuple to customize unwrap behavior
  [mapcat((x) => x), false],
  // or provide as before (with current unwrap behavior)
  map((x) => x)
)
```

IMHO that's the best/safest solution, also ensuring non-breaking behavior in existing userland code...
