### ISSUE TITLE
[@thi.ng/ksuid] KSUID32 overflows during 2088

### ISSUE THREAD

**Issue by aelr** [thi-ng/umbrella#403]
This code using KSUID32 fails:
```
idgen.fromEpoch(new Date("2089-01-01").getTime())
```

It throws at https://github.com/aelr/umbrella/blob/develop/packages/ksuid/src/aksuid.ts#L77:
```
assert(t >= 0, "configured base epoch must be in the past");
```
For this specific case, `t = -2139591296`

Also, should the error message be, "configured base epoch must _not_ be in the past"?

**Comment by postspectacular** [comment]
Thanks & fixed! :) Also updated the readme to point out the new max date for the KSUID32 implementation. With the default offset, the max. supported date for KSUID32 is 2156-10-20T18:54:55Z. If you need even further ahead, you'll have to switch to one of the other impls (KSUID64 or ULID)

**Comment by postspectacular** [comment]
Btw. @aelr, the fix has been released yesterday a [v3.1.15](https://github.com/thi-ng/umbrella/blob/develop/packages/ksuid/CHANGELOG.md#3115-2023-08-06)

**Comment by aelr** [comment]
Thank you!

**Comment by postspectacular** [comment]
Please let me know if that's working for you now. If you're using these IDs for a new project, you might also be able to adjust the time shift to an offset around now and so gain an additional 3 years since the initial version of this library... You can do that like so:

```ts
const idgen = defKSUID32({ epoch: new Date("2023-08-08").getTime() });
```

**Comment by aelr** [comment]
I actually shifted away from KSUID after checking the perf numbers. Instead I'm using `@thi.ng/base-n` to base62-encode `Date.now()` and appending a `nanoid` for the random bits. On my laptop, the ops/sec is 1.2 million/sec vs 90k/sec.
