### ISSUE TITLE
[vectors] Vec2 missing x and y coordinate

### ISSUE THREAD

**Issue by dennemark** [thi-ng/umbrella#432]
I did not upgrade @thi.ng/vectors for a while. Was on version 7.5.14 and now upgraded to 7.8.9
I can´t really imagine it, but it seems like the x and y coordinates on a Vec2 class are missing.
```js
console.log(new vec.Vec2([0, 1]))
//Vec2 {
//  buf: [ 0, 1 ],
//  offset: 0,
//  stride: 1,
//  x: undefined,
//  y: undefined
//}
```
Tried to trace it back to: https://github.com/thi-ng/umbrella/blob/develop/packages/vectors/src/compile/accessors.ts#L2
Or it is just the missing assignment in constructor of Vec2. 
Used yarn patch to solve it, by adding the following lines
```Diff
@@ -62,6 +62,8 @@ class Vec2 extends AVec {
   y;
   constructor(buf, offset = 0, stride = 1) {
     super(buf || [0, 0], offset, stride);
+    this.x = buf ? buf[0] : 0
+    this.y = buf ? buf[1] : 0
   }
   [Symbol.iterator]() {
     return stridedValues(this.buf, 2, this.offset, this.stride);
@@ -69,6 +71,18 @@ class Vec2 extends AVec {
   get length() {
     return 2;
   }
+  get x() {
+    return this.buf[this.offset]
+  }
+  get y() {
+    return this.buf[this.offset + 1 * this.stride]
+  }
+  set x(value) {
+    this.buf[this.offset] = value
+  }
+  set y(value) {
+    this.buf[this.offset + 1 * this.stride] = value
+  }
```
Is this reproducable?

**Comment by dennemark** [comment]
Thanks so much! Super fast :D I was already wondering if maybe vite cache was messed up... Going to try out later :)

**Comment by postspectacular** [comment]
Customer sevice! :) It's uploading now, but maybe give it another 5 mins... it will be v7.8.10!
