### ISSUE TITLE
[color]  ? [binary]  Comparison with -0 using the "===" operator will also match 0 [equals-negative-zero]

### ISSUE THREAD

**Issue by bit-app-3000** [thi-ng/umbrella#450]
```
import { colorFromRange, css } from '@thi.ng/color'
export const color = () => css(colorFromRange('neutral'))
```

[DEBUG] Comparison with -0 using the "===" operator will also match 0 [equals-negative-zero]

    ../../node_modules/@thi.ng/binary/float.js:22:12:
      22 │   if (x === -0)
         ╵             ~~

  Floating-point equality is defined such that 0 and -0 are equal, so "x === -0" returns true for
  both 0 and -0. You need to use "Object.is(x, -0)" instead to test for -0.

**Comment by postspectacular** [comment]
Thank you @bit-app-3000 - I'm aware of this, but this warning can be ignored in this case, since the full line here reads:

```ts
if (x === -0) x = 0;
```

So regardless if `0` or `-0`, I want both cases to be `0`.

In fact, this line could/should be written as an early bail out:

```ts
if (x === -0) return 0;
```

**Comment by bit-app-3000** [comment]
maybe it will be more convenient?

` If ( !Math.abs(x) ) return  0`
