### ISSUE TITLE
[examples] Issue running the examples (failed to resolve entry for package)

### ISSUE THREAD

**Issue by arnaudchenyensu** [thi-ng/umbrella#458]
Hi,

I'm having some issues running the examples. I cloned the repo, `cd examples/stacked-layout`, `yarn install` and `yarn start` but then I have the following error:

<img width="923" alt="Screen Shot 2024-03-09 at 12 51 56 pm" src="https://github.com/thi-ng/umbrella/assets/1472712/b7ae9607-a6cd-44b2-94f1-bfaa7427c053">

Did I miss something?

Best,
Arnaud.

**Comment by postspectacular** [comment]
Hi @arnaudchenyensu - the examples are all configured to use local workspace/repo references and so the build instructions are slightly different than what you've done here (also linked from the readme of each example):

https://github.com/thi-ng/umbrella/wiki/Example-build-instructions

The main difference is that you first need to build the entire repo (once) before being able to run any of the examples locally... Hope that helps!

**Comment by arnaudchenyensu** [comment]
Thank you! My bad, I misread, I thought the first step was optional...

**Comment by postspectacular** [comment]
@arnaudchenyensu - yeah, sorry it's not optional. The main reason for this setup is to ensure the 150+ examples aren't cluttered with their own individual `node_modules` dirs and also to force examples using always the latest version of each package (i.e. those in the workspace under `/packages/*`, just keeps things much faster & easier to maintain...)
