### ISSUE TITLE
[shader-ast]  "Building a shader graph editor (WebGL, shader AST transpiler, UI)"

### ISSUE THREAD

**Issue by johnkorzhuk** [thi-ng/umbrella#465]
In the readme of [thi.ng/shader-ast](https://thi.ng/shader-ast) the link to the Youtube video called "Building a shader graph editor (WebGL, shader AST transpiler, UI)" is no longer up. Is there anywhere else that I can find this video?

**Comment by postspectacular** [comment]
Hi @johnkorzhuk - I delete my old Google account and with it all YT content is gone too. I'll re-upload the videos to makertube.net in the next day and report back here...

**Comment by postspectacular** [comment]
I just updated all the readmes with new links to my Makertube channel: https://makertube.net/c/thingumbrella/videos

Thanks again for the nudge! 👍 😅
