### ISSUE TITLE
[rdom]  SVG el add class > Uncaught (in promise) TypeError

### ISSUE THREAD

**Issue by bt-3000** [thi-ng/umbrella#469]
```
const Loader = [
     'svg', { class: 'loader' },
     [  'path', { d: '...' } ]
  ]
```

**Uncaught (in promise) TypeError: setting getter-only property "className"**

**Comment by postspectacular** [comment]
@bt-3000 - gonna look into it tomorrow, might have to do with a recent update to attrib vs. property setters... reporting back ASAP!
