### ISSUE TITLE
[hdom] update diffTree docs

### ISSUE THREAD

**Issue by vorg** [thi-ng/umbrella#47]
Where do i get `HDOMImplementation` for the new `diffTree` implementation?

I've been using hdom@3 for quite while as follows

```javascript
const curr = normalizeTree(render, null, [0], true, true)
if (curr !== null) {
    diffElement(rootElement, prev, curr)
    prev = curr
}
````

I'm trying to port it to v5 and use `diffTree` as before

> Takes a DOM root element and two hiccup trees, prev and curr. 

but i'm getting `Trigger "in" failed: undefined is not an object (evaluating 'curr[1]')`

```javascript
const curr = normalizeTree({}, render)
if (curr !== null) {
    diffTree(rootElement, prev, curr)
    prev = curr
}
```

after looking at the source I can see that first param is `opts` like in `normalizeTree` but second is `impl:HDOMImplementation` and i'm not sure where do i get that from.

**Comment by vorg** [comment]
Hmm. Unfortunately not. As  `import { DEFAULT_IMPL } from "./default"` is not accessible via `require('@thi.ng/hdom').default` I would need to get it through `require('@thi.ng/hdom/default')` i guess? But that I can't do in my project..

**Comment by vorg** [comment]
Is `diffTree` meant to be an internal API? I need it to have control over when in my main app RAF the diffing happens.

**Comment by postspectacular** [comment]
No it's not meant to be internal. However I forgot to add the `DEFAULT_IMPL` to the entire module's re-exports. Just pushed a new version: 5.0.3.

You should now at least be able to:

```
import { DEFAULT_IMPL } from "@thi.ng/hdom";

// or

require("@thi.ng/hdom").DEFAULT_IMPL
```

**Comment by postspectacular** [comment]
So to update your example do:

```
const curr = normalizeTree({}, render)
if (curr !== null) {
    diffTree({root: rootElement}, DEFAULT_IMPL, prev, curr)
    prev = curr
}
```

**Comment by vorg** [comment]
I had to provide root as 3rd parameter and append 0 at the end as in [start.ts](https://github.com/thi-ng/umbrella/blob/master/packages/hdom/src/start.ts#L50)

```javascript
const hdom = require('@thi.ng/hdom')
const diffTree = require('@thi.ng/hdom').diffTree
const normalizeTree = require('@thi.ng/hdom').normalizeTree

diffTree({ }, hdom.DEFAULT_IMPL, rootElement, prev, curr, 0)
```

Up and running now.

**Comment by postspectacular** [comment]
👍 Yes, sorry - it's late :)
