### ISSUE TITLE
@thi.ng/ksuid has issue with Webpack

### ISSUE THREAD

**Issue by Mitul-Webelight** [thi-ng/umbrella#482]
```
export const generateKSUID = async (prefix: string) => {
  const ksuidModule = await import("@thi.ng/ksuid/ulid");

  const { ULID } = ksuidModule;
  const ksuid = new ULID();

  return `${prefix}_${ksuid.next()}`;
};
```
I'm working in nestjs + typorm + mysql
so this is how I'm using this package to generate unique Id
but the problem was when i build my project with webpack and then run that build it return an error while I run any create query.

> require() of ES Module /"path of my project directory"/node_modules/.pnpm/@thi.ng+ksuid@3.2.55/node_modules/@thi.ng/ksuid/ulid.js from /"path of my project directory"/dist/main.js not supported.\nInstead change the require of ulid.js in /"path of my project directory"/dist/main.js to a dynamic import() which is available in all CommonJS modules.

this is the error which I'm facing when I run create query and my tsconfig file is same as [https://github.com/thi-ng/umbrella/blob/develop/tsconfig.json](https://github.com/thi-ng/umbrella/blob/develop/tsconfig.json)

can anyone help me for the same ?

**Comment by postspectacular** [comment]
@Mitul-Webelight I don't have any experience with webpack (at least not in the last 4 years), but the mention of `require()` in the error message seems like there's some transpilation involved (at least for CJS)? For a while now all thi.ng package have only been distributed as ESM, and dealing with CJS is left as an exercise to the reader, so to speak... It was just a nightmare to deal with all these flavors of JS and I was glad to leave it behind...

Did you you try changing the import to import the full package:

```js
const ksuidModule = await import("@thi.ng/ksuid");
```

Other than that, I'm really sorry I can't be of more help, maybe someone else can chime in...?
