### ISSUE TITLE
[bencode] Encoding an object with `length` field

### ISSUE THREAD

**Issue by quyse** [thi-ng/umbrella#485]
Hi,

Thanks for the bencode library! The following code crashes with "not a function or its return value is not iterable":

```typescript
import {
  encode as bencodeEncode,
} from '@thi.ng/bencode';

bencodeEncode({
  length: 123,
});
```

Apparently that's because the code tries to encode this object as a list and not a dict, because it uses `isArrayLike` to check, and `isArrayLike` just checks if there's `length` field. If I change `length` to `length1`, the code succeeds.

Any standard torrent file uses fields named `length` in array of files inside the torrent, so it is quite necessary. Is there a way to encode an object with `length` field?

**Comment by postspectacular** [comment]
Ohhh, that's a good find & will be pretty straightforward to fix... I'm in the middle of some large repo-wide refactoring/restructuring, but will get this one out later today... thanks for reporting! 👍

**Comment by postspectacular** [comment]
@quyse - so i just fixed it, but release will only be later this weekend. Sorry to keep you waiting...

**Comment by postspectacular** [comment]
Hi @quyse - the new version is now released, thanks again! 👍 

https://github.com/thi-ng/umbrella/blob/develop/packages/bencode/CHANGELOG.md#21128-2024-07-22
