### ISSUE TITLE
[ramp] ramp behavior is different when number of stops < 256

### ISSUE THREAD

**Issue by robertoranon** [thi-ng/umbrella#494]
Hi :)

   in ramp.ts, the `timeIndex` function uses binary search to find the time index when number stops > 256 (https://github.com/thi-ng/umbrella/blob/34ac95538d96f046090fef5fd3a1dc36d54663d5/packages/ramp/src/ramp.ts#L163)
   
 If the exact time can't be found, binary search returns a negative index (https://github.com/thi-ng/umbrella/blob/34ac95538d96f046090fef5fd3a1dc36d54663d5/packages/arrays/src/binary-search.ts#L58), which then causes the at() function to return the first stop value:
 
         return i < 0 ? first[1] : i >= n ? last[1] : impl.at(stops, i, t);
         
I would expect it to return `impl.at(stops, -i, t)` in this case ... where am I wrong?

**Comment by postspectacular** [comment]
Just released the fix as v3.3.12 - thank you again!

**Comment by robertoranon** [comment]
Thanks to you! I should have provided a PR in the first place, I wasn't 100% sure I was right

**Comment by postspectacular** [comment]
Ah, don't worry! The fix was actually slightly different, and I also added some tests to make sure:

https://github.com/thi-ng/umbrella/blob/39a504b5e15f38580e53057e3127e8170f2b994e/packages/ramp/src/ramp.ts#L169
