### ISSUE TITLE
rfn is not iterable

### ISSUE THREAD

**Issue by pedroteixeira** [thi-ng/umbrella#5]
Hi, 

Tried running the example from the readme but it raises an exception:

```
import { Channel } from "@thi.ng/csp";
import * as tx from "@thi.ng/transducers";

Channel.merge([
  Channel.range(0, 3),
  Channel.range(10, 15),
  Channel.range(100, 110)
]).reduce(tx.push).then(console.log);
```

```
channel.js:363 Uncaught (in promise) TypeError: rfn is not iterable
    at Channel.<anonymous> (channel.js:363)
```

**Comment by postspectacular** [comment]
Hey - thanks for reporting. But this is just a typo in the readme.. Even though reducers are just 3-element arrays, a while ago I unified all bundled reducers to be functions (since a lot of them are). So just change the last line to:

```
]).reduce(tx.push()).then(console.log);
```
