### ISSUE TITLE
[hdom] IE11 Support

### ISSUE THREAD

**Issue by vorg** [thi-ng/umbrella#63]
IE doesn't support ChildNode.remove() (and probably other things) and throws ``TypeError: Object doesn't support property or method 'remove'`` here https://github.com/thi-ng/umbrella/blob/e36a7ee080147d3ccbb464b0536c0ccc74ae1d01/packages/hdom/src/dom.ts#L307

Any particular reason not to use `parent.removeChild(child)`?

In the meantime I'm using polyfill from here https://developer.mozilla.org/en-US/docs/Web/API/ChildNode/remove#Polyfill

**Comment by postspectacular** [comment]
Thanks Marcin! No other particular reason than my own ignorance of IE11 quirks. Just pushed v6.0.4 which should fix this. Please do let me know, since I don't have an easy way to test this myself right now...
