### ISSUE TITLE
[vectors] static scaleWithCenter produces NaNs

### ISSUE THREAD

**Issue by acarabott** [thi-ng/umbrella#65]
```ts
import { Mat23, Vec2 } from "@thi.ng/vectors";
console.log(Mat23.scaleWithCenter(new Vec2([1, 1]), 1, 1).buf);
// [1, 0, 0, 1, NaN, NaN]
```

I believe it's because the `im` param (matrix index?) is missing in the call to `scaleWithCenter23`. Default parameters considered harmful? :)

Putting in a fix now...

**Comment by postspectacular** [comment]
yep, see my comment on your PR...
