### ISSUE TITLE
hiccup-dom status?

### ISSUE THREAD

**Issue by vemv** [thi-ng/umbrella#7]
Hi there!

hiccup-dom looking neat, was missing something like that after jumping cljs -> jsx.

Is the project still to be considered alpha?

Would be a great thing to add that to the README.

Cheers - Victor

**Comment by postspectacular** [comment]
Thanks, @vemv - good idea! Alas, I always have a hard time classifying things as alpha, beta etc. where do you draw the line? Personally, I'd say it's a beta. The module is used in at least four projects in production and together they use pretty much all current features and we haven't run into any probs so far. However, a lot more documentation and examples are needed in order for public consumption to pick up. There's also work underway on a support module with customizable components, but not yet on GH (hoping tocheck in the more complete ones on weekend). Another blog post about the more advanced features & usage patterns is in the works too. If you have any other recommendations, please share! :)

**Comment by vemv** [comment]
Thanks much for the clarification + commit!

And apologies for the absence I had been busy.

Looking forward to try out the package when the opportunity arises!

**Comment by postspectacular** [comment]
No worries! :)
