### ISSUE TITLE
[strings] SyntaxError: Invalid regular expression: invalid group specifier name

### ISSUE THREAD

**Issue by vorg** [thi-ng/umbrella#70]
```javascript
const kebab = (x, delim = "-") => lower(x.replace(/(?<=[a-z0-9\u00e0-\u00fd])(?=[A-Z\u00c0-\u00dd])/g, (_, i) => (i ? delim : "")));
```

Is broken in Safari and Firefox

**Comment by vorg** [comment]
Oh actually it is a TODO in the source code https://github.com/thi-ng/umbrella/blob/b9cea8cc981702caf6d69dc46d5f01ab5af2aa5f/packages/strings/src/case.ts#L31

**Comment by vorg** [comment]
Any suggestions on how to mitigate? It prevents me from using `hiccup-svg`

**Comment by gavinpc-mindgrub** [comment]
@postspectacular you are one-of-a-kind.

**Comment by postspectacular** [comment]
@vorg released as 1.0.2

@gavinpc-mindgrub i'll take this a compliment... ;)

**Comment by gavinpc-mindgrub** [comment]
@postspectacular, indeed.  I would put @thi.ng/umbrella on a very short list of technologies that I have found life-changing, and I started programming in 1988.  I have created an internal research project based heavily on these tools, and would love to discuss if you are interested, gcannizzaro@mindgrub.com.

I had run into the OP's issue and had a mitigation somewhere in my notes, but you fixed it before I could find it.  Hence my comment.

**Comment by postspectacular** [comment]
That's great to hear @gavinpc-mindgrub - will shoot you an email over the weekend... (btw. i started coding the same year)

As for the issue at hand: I'm trying to regularly test various pieces in FF & Safari, but often I'm just pressed for time or forget and I'm no expert keeping the caniuse stuff in my head. The regex in question works fine in Node 11 (maybe even in 10) and Chrome, so I guess I just have to be more defensive with using new syntax features (at least those which can't be transpiled)
