### ISSUE TITLE
[hdom] skipped element produces duplicates if empty

### ISSUE THREAD

**Issue by vorg** [thi-ng/umbrella#72]
Consider following render loop

```javascript
const { start } = require("@thi.ng/hdom");

const text = "only-once ";

let frame = 0;
const render = () => {
  if (frame++ % 100 === 0) {
    return ["div#app", text];
  } else {
    return ["div", { __skip: true }];
  }
};

start(render, { root: document.body });
```

## Result

Over time there is only one `#app` dom element (correct) but it has multiple children text nodes `only-once` (incorrect)

```
only-once only-once only-once only-once only-once
```

## Expected result

There is only one `#app` dom element and it has one child text node `only-once`

```
only-once
```

## Solution

Adding any content (e.g. `''`) to the skipped div properly cleans the children on next render

```javascript
return ["div", { __skip: true }, ''];
```

## Discussion

In [hdom-skip](https://github.com/thi-ng/umbrella/blob/master/examples/hdom-skip/src/index.ts#L29) example it's written `// dummy content (could be an empty div)`. Turns out it can't be an empty div.

**Comment by vorg** [comment]
Runnable example https://codesandbox.io/s/xjmkwrlv5w

**Comment by postspectacular** [comment]
Thanks, as always, @vorg! That's a good find and the behavior actually makes sense. During an update cycle hdom only has access to the previous tree and so when if that prev tree is just `["div", { __skip: true }]` and the new one has no `__skip` again any child elements it will be simply considered an addition... I will update `normalizeTree()` to ensure a skipped element will always have a dummy child.

**Comment by postspectacular** [comment]
So [this commit](https://github.com/thi-ng/umbrella/commit/3ed4ea12fa62bf8700bf31a481070bbe6a94729f) seems to fix it, but will have to do some more testing before doing a new release... also will update docs with some more notes about expected behaviors

**Comment by vorg** [comment]
So in 8.0.6 it does work with 1 child but fails if i have more... Not sure what's the proper usage of __skip then... I'm trying to replicate React's "shouldComponentUpdate" and avoid re-building, re-diffing and re-rendering huge SVG map.

Updated example with 2 children https://codesandbox.io/s/hdomskip-2wkm4

**Comment by postspectacular** [comment]
hey @vorg - thanks for discovering this weirdness. i've started re-working the `__skip` diff handling to be less brittle and now using this behavior (also documented in the readme):

> Once a previously skipped element is re-enabled (i.e. its `__skip` attrib is now falsy again), the element's entire sub-tree is re-created, but any lifecycle `init()` methods within that sub-tree will not be re-executed.

I've also forked & updated the sandbox example to use a new hdom prerelease version (`9.0.0-alpha1`): https://codesandbox.io/s/hdomskip-22gon

It'd be great to hear back if that works for your use case. I'll be doing more testing myself to see what other impact that change in behavior might have caused...

**Comment by postspectacular** [comment]
Here's another `__skip` related example: https://demo.thi.ng/umbrella/hdom-skip-nested/

**Comment by postspectacular** [comment]
Hey @vorg - did you have a chance to try out that new version (see above) with your project? I was going to push new releases later this week and would be great to hear back or else will defer... 
Danke! :)

**Comment by postspectacular** [comment]
Thanks, Marcin! I've done some more tests tonight too, so thinking this might be good to go... just need to update readme some more

**Comment by loganpowell** [comment]
@vorg can this issue be closed?

**Comment by postspectacular** [comment]
@loganpowell i think this will close automatically once i merge the feature branch back into master...
