### ISSUE TITLE
[umbrella/hdom] textarea - displaying and changing data at the same time

### ISSUE THREAD

**Issue by mako1131** [thi-ng/umbrella#76]
Hello,
if I want a `<textarea>` to render a piece of data, but also to be able to change this data by typing in the textarea, strange things happen. In chrome for example, I lose cursor focus from the textarea after the first letter is written. In Firefox the cursor is not lost, but the textareas, that has been written in, will just stop updating the data.
With `<input>` for example, it's working correctly. I understand, that input's value is attribute, and textarea's value is in it's innerHTML and the update/change is probably handled differently.

I tried this piece of code:
```
let txt = 'test';

const textArea = () => {
    return () => ['div',
        ['textarea', { oninput: (e) => txt = e.target.value }, txt],
        ['div', txt]
    ]
}

const input = () => {
    return () =>
        ['div',
            ['input', { type: "text", value: txt, oninput: (e) => txt = e.target.value }],
            ['div', txt]
        ]
}

const app =
    ["div#app",
        textArea(),
        textArea(),
        input(),
        input(),
        () => ['div', txt]
    ];

start(app);
```

The expected behaviour for me was to any input / textarea to display the same data, and any change made in any of them to be mirrored in all of them.
Am I doing something wrong? Or did I not understand something correctly? I started playing with hdom just today - is something like this possible?

**Comment by canfan** [comment]
This code below should work, notice the added `() =>` in app. The issue here is that your `app` needs to be a function for `start` to update it every frame. 

```ts
const app = () =>
    ["div#app",
        textArea(),
        textArea(),
        input(),
        input(),
        () => ['div', txt]
    ];
```

**Comment by postspectacular** [comment]
Hey @mako1131 - thanks for reminding me to document this properly. this one of the very rare exceptions which one could consider exceptional behavior. The solution is: Don't assign the body of the textarea as body/child of the element, but assign it to the `value` attrib (as with `input` fields). This is because the `value` update has the cursor backup/restore logic and keeping that for textarea too just made things more simple.

Please let's keep this open until I've updated the hdom readme. thx!

**Comment by postspectacular** [comment]
@mako1131 also see this example here:

https://github.com/thi-ng/umbrella/blob/master/examples/markdown/
In situ: https://github.com/thi-ng/umbrella/blob/master/examples/markdown/src/index.ts#L40

**Comment by postspectacular** [comment]
Added a note about the `value` attrib handling to the readme:

https://github.com/thi-ng/umbrella/tree/master/packages/hdom#value-attribute-handling
