### ISSUE TITLE
[umbrella/hiccup] [umbrella/checks] Attributes not recognized if hiccup generated in a different context

### ISSUE THREAD

**Issue by eccentric-j** [thi-ng/umbrella#77]
# Reproduction
1. Copy the script below into `vm.js`:
    ```js
    const hiccup = require('@thi.ng/hiccup');
    const vm = require('vm');

    const script = new vm.Script(`["link", {rel: "stylesheet"}]`);
    const myContextView = script.runInNewContext({});

    console.log("normal", hiccup.serialize(["link", {rel: "stylesheet"}]));
    console.log("from context", hiccup.serialize(myContextView));
    ```
2. Run `node vm.js`

## Expected
- Both log statements should fire
- Hiccup should transform both hiccup arrays into `<link rel="stylesheet" />`.

## Actual
- First console.log with hiccup array in same context works
- Second console.log raises an error due to the attributes of the link being intrepreted as body content.

## Research
- Digging into this, it comes down entirely to the checks [isPlainObject](https://github.com/thi-ng/umbrella/blob/%40thi.ng/vectors%402.4.1/packages/checks/src/is-plain-object.ts) predicate.
- The link attributes object created in the context has a different prototype instance than the `OBJP` prototype.

## Solution
- Monkey-patched a solution by replacing the checks.isPlainObject predicate to the following:
    ```js
    const checks = require("@thi.ng/checks");

    checks.isPlainObject = function isPlainObject (x) {
    return Object.prototype.toString.call(x) === "[object Object]"
        && x
        && x.constructor
        && x.constructor.toString() === "function Object() { [native code] }";
    }
    ```
- While it appears to be working, unsure of long-term implications.

## Environment
- Node: `11`
- thi.ng hiccup: `3.1.2` 

## Notes
- Encountered this while using the hiccup library within a self-hosted cljs environment
- What is the end goal of this function?
- I recognize this is a hard problem to solve in JS since most values are objects: how do you determine when a value is not a special object?
- Please let me know if I can provide any more information to help

**Comment by postspectacular** [comment]
wow, that's the first time I've heard about the `vm` pkg and it makes sense that the `Object.prototype` of that sandbox context will be a different identity than in the main ctx. But still, admittedly this use case is a pretty special case...

I will test your `isPlainObject` changes and see what the impact is, then report back. Did you already check if the tests of the @thi.ng/checks pkg are still working with your monkey patch? I remember reading some time ago that using `Object.constructor` for these kinds of tests is discouraged, but can't find the link right now...

In anyway, thanks a lot for reporting!

**Comment by postspectacular** [comment]
Found the link: http://xahlee.info/js/javascript_object_constructor_property.html - there's a section called: "Do Not Use the Constructor Property" - but I think in this case here we should be fine...

The other thing I'm a bit concerned about with your version of `isPlainObject` is the `.toString()` call and its impact on overall performance. If this turns out to have a noticeable impact, then I'm not sure if the change for this special use case justifies the cost and we will have to find another solution...

**Comment by postspectacular** [comment]
@eccentric-j So just as I thought, the `x.constructor.toString()` call makes that new version a whopping 4x slower than the existing version...

```js
const b = require("@thi.ng/bench");
const c = require("@thi.ng/checks");

const OBJ_TOSTRING = Object.prototype.toString;
const OBJ_TYPE = "[object Object]";
const OBJ_CTOR = "function Object() { [native code] }";

const isPlainObject2 = (x) => {
    return (
        OBJ_TOSTRING.call(x) === OBJ_TYPE &&
        x.constructor &&
        x.constructor.toString() === OBJ_CTOR
    );
};

const foo = () => [
    c.isPlainObject({}),
    c.isPlainObject("a"),
    c.isPlainObject(null),
    c.isPlainObject(2),
    c.isPlainObject(undefined)
];

const foo2 = () => [
    isPlainObject2({}),
    isPlainObject2("a"),
    isPlainObject2(null),
    isPlainObject2(2),
    isPlainObject2(undefined)
];

b.bench(() => b.bench(foo, 1e6), 10);
// 92ms
// 84ms
// 84ms
// 85ms
// 83ms
// 84ms
// 83ms
// 84ms
// 84ms
// 85ms
// 861ms

b.bench(() => b.bench(foo2, 1e6), 10);
// 358ms
// 355ms
// 359ms
// 359ms
// 360ms
// 357ms
// 354ms
// 355ms
// 355ms
// 357ms
// 3569ms
```

Not giving up on this just yet, but right now it causes a noticeable fps drop in the [hdom-benchmark](https://demo.thi.ng/umbrella/hdom-benchmark2/)...
 
Another question: is it possible for you to execute the vm script in the current VM context? I.e. using `myContextView = script.runInThisContext({});`?

**Comment by gavinpc-mindgrub** [comment]
@postspectacular, for what it's worth, this is also true in the browser when crossing frame boundaries, which you can see in the console:

```javascript
const iframe = document.body.appendChild(document.createElement('iframe'))
undefined
iframe.contentWindow.Object.prototype === Object.prototype
false
```
I wouldn't expect to run against this, but thought this may be helpful for testing or documenting `isPlainObject`.

**Comment by postspectacular** [comment]
@gavinpc-mindgrub maybe we just have to swallow this bitter pill then...

**Comment by eccentric-j** [comment]
My use case in particular is using https://www.npmjs.com/package/clojurescript which executes the cljs in another context.

That said, I see the short comings of my solution. From my understanding the goal isn't to compare instances, it's to determine if a value is a plain JS object. In theory that suggests there should be a reliable way to do this that doesn't introduce breaking changes or degrade performance.

Can I continue researching alternative implementations? I tested with underscore's implementation, there's a slight hit in performance but not by as much.

 ```js
const assert = require("assert");
const b = require("@thi.ng/bench");
const c = require("@thi.ng/checks");

const OBJ_TOSTRING = Object.prototype.toString;
const OBJ_TYPE = "[object Object]";
const OBJ_CTOR = "function Object() { [native code] }";

const isPlainObject2 = (x) => {
  if (OBJ_TOSTRING.call(x) !== OBJ_TYPE) {
    return false;
  }

  let p = Object.getPrototypeOf(x);

  if (p === null) {
    return true
  }

  let proto = x
  let p2 = null;

  while ((p2 = Object.getPrototypeOf(proto)) !== null) {
    proto = p2;
  }

  return p === proto;
};

function CustomObj () {

}

const foo = () => [
  assert.ok(c.isPlainObject({})),
  assert.ok(!c.isPlainObject("a")),
  assert.ok(!c.isPlainObject(null)),
  assert.ok(!c.isPlainObject(2)),
  assert.ok(!c.isPlainObject(undefined)),
  assert.ok(!c.isPlainObject(new CustomObj())),
];

// 248ms
// 220ms
// 212ms
// 212ms
// 213ms
// 215ms
// 213ms
// 213ms
// 222ms
// 210ms
// 2201ms

const foo2 = () => [
  assert.ok(isPlainObject2({})),
  assert.ok(!isPlainObject2("a")),
  assert.ok(!isPlainObject2(null)),
  assert.ok(!isPlainObject2(2)),
  assert.ok(!isPlainObject2(undefined)),
  assert.ok(!isPlainObject2(new CustomObj())),
];

// 352ms
// 332ms
// 339ms
// 336ms
// 334ms
// 332ms
// 337ms
// 337ms
// 331ms
// 336ms
// 3370ms

b.bench(() => b.bench(foo, 1e6), 10);
b.bench(() => b.bench(foo2, 1e6), 10);
```

Another option could be to use a deepEqual operator right? If the obj's prototype is equal to an empty object it's a plain JS object?

**Comment by postspectacular** [comment]
Thanks so much, @eccentric-j - this looks more promising indeed, so by all means I'd very appreciate if you can/want to research further. I've tested lodash so far, but it's even slower than what I posted, and I actually previously had something similar to the prototype chain walking used in the underscore version, but then replaced it for unknown reasons (bad memory! :)... will check it out later today

**Comment by postspectacular** [comment]
@eccentric-j Just plugged it in and it seems the overall speed hit is really minor/acceptable. Will not push it just yet, to give you more time and al myself for further testing. But thanks so far!

**Comment by eccentric-j** [comment]
You're welcome @postspectacular, and thank you for being so responsive.

Another path that came to mind on my walk to the office may be to update hiccup to use more of an https://github.com/lodash/lodash/blob/master/isObjectLike.js test or something more custom to determine if the second item in a hiccup array can be used as attributes versus a stricter is plain object check. 

This way we wouldn't need to change the behavior of isPlainObject as the issue is hiccup's argument juggling in a case like this. What are your thoughts?

**Comment by postspectacular** [comment]
I thought about this too since there's no *real* need for this to be strictly a vanilla JS object. It was more of a precaution and trying to encourage a certain style, plus I had hopes to define a TypeScript type for these hiccup arrays, however TS still (maybe never) doesn't support recursive tuple types (AFAIK)... this would definitely be the easiest option, but am grateful for the new findings thus far...

Btw. We already have such an "object like" check: [isObject](https://github.com/thi-ng/umbrella/blob/%40thi.ng/vectors%402.4.1/packages/checks/src/is-object.ts)

**Comment by gavinpc-mindgrub** [comment]
Good call @eccentric-j.  Here is a simplified version that I believe is equivalent:

```typescript
const isPlainObject3 = x =>
  x != null &&
  typeof x === "object" &&
  Object.getPrototypeOf(Object.getPrototypeOf(x)) === null;
```

I modified the bench tests to include plain and custom objects from a VM:

```javascript
const custom_from_other_context = vm.runInNewContext("class A {}; new A();");
const plain_from_other_context = vm.runInNewContext("({})");

const against = fn => () => [
  assert.ok(fn({})),
  //assert.ok(fn(plain_from_other_context)),
  assert.ok(!fn("a")),
  assert.ok(!fn(null)),
  assert.ok(!fn(2)),
  assert.ok(!fn(undefined)),
  assert.ok(!fn(tx.map(x => x, []))),
  assert.ok(!fn(new CustomObj())),
  assert.ok(!fn(custom_from_other_context))
];

function go() {
  console.log(`== check`);
  b.bench(() => b.bench(against(c.isPlainObject), 1e6), 10);

  console.log(`== underscore`);
  b.bench(() => b.bench(against(isPlainObject2), 1e6), 10);

  console.log(`== custom`);
  b.bench(() => b.bench(against(isPlainObject3), 1e6), 10);
}

go();
```

On my machine, results look something like this:

```
== check
352ms
380ms
376ms
378ms
380ms
375ms
396ms
371ms
388ms
372ms
3770ms
== underscore
517ms
510ms
508ms
505ms
503ms
511ms
507ms
503ms
506ms
525ms
5095ms
== custom
349ms
345ms
347ms
347ms
354ms
340ms
341ms
347ms
340ms
351ms
3463ms
```

(Note that the overall times are higher than earlier posts because I added assertions.)

If you uncomment the `plain_from_other_context` assertion and comment the `c.isPlainObject` batch, the tests still pass.

Note that the `typeof x === "object"` check doesn't actually change the results, but it does speed things up considerably (by avoiding `Object.getPrototypeOf` calls for primitives).

I have not run this against the `@thi.ng/check` tests.

**Comment by postspectacular** [comment]
This is ++great @gavinpc-mindgrub - thank you! Will give it a whirl...

**Comment by gavinpc-mindgrub** [comment]
Ehhh, so that breaks on objects with *no* prototype, such as you get from `Object.create(null)`.

```javascript
  assert.ok(fn(Object.create(null))),
```

This is covered in the underscore version by a null check.  I've updated accordingly:

```javascript
// Object with no prototype is still considered a plain object.
const isPlainObject3 = x => {
  if (x == null || typeof x !== "object") return false;
  const p1 = Object.getPrototypeOf(x);
  return p1 === null || Object.getPrototypeOf(p1) === null;
};
```

Results indicate it's still worth avoiding the loop, though.

```
== underscore
736ms
745ms
731ms
757ms
724ms
755ms
774ms
723ms
735ms
727ms
7408ms
== custom
473ms
469ms
469ms
470ms
457ms
465ms
485ms
466ms
470ms
463ms
4687ms
```

**Comment by eccentric-j** [comment]
Should Object.create(null) fail? In most circumstances would an object created that way be problematic in use cases expecting a plain object?

**Comment by gavinpc-mindgrub** [comment]
@eccentric-j I can't imagine when it would be necessary, but since it is in fact possible, it's technically never "safe" to assume `Object`-defined members (hence the static functions on `Object`)—or in this case that the inner `getPrototypeOf` call won't return `null`.

Regardless, people definitely do it.  [Here's some discussion on SO](https://stackoverflow.com/q/32262809).

**Comment by eccentric-j** [comment]
@gavinpc-mindgrub Thanks for explaining! I missed the nuance that it SHOULD return true on `Object.create(null)`, I had interpreted it incorrectly thinking that the fix would make it return false.

@postspectacular I can confirm using isObject in place of isPlainObject in hiccup's normalize function is works in this use case where a different context is used.

Do you want to continue exploring isPlainObject implementations or should I make a PR to update the normalize function?

**Comment by postspectacular** [comment]
@eccentric-j @gavinpc-mindgrub hey sorry, i've been updating and testing everything for the past 2 hours and missed your recent replies. @gavinpc-mindgrub's version is working great AFAIK and I've added the new cases to the unit tests as well... about to publish everything, but still a few more minor things left to do... thank you both!!

**Comment by eccentric-j** [comment]
Awesome thanks so much @postspectacular and @gavinpc-mindgrub!

**Comment by postspectacular** [comment]
Publishing as I type... new version will be up in a few mins: `"@thi.ng/checks": "^2.1.2"` - thanks again & pls let me know if it works for you now...

**Comment by eccentric-j** [comment]
It's working! Thanks again. 🚀
