### ISSUE TITLE
[Build] vec-utils.js:16 regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by nkint** [thi-ng/umbrella#78]
Hi!
I'm trying to build a project largely based on @thi.ng with parcel-bundler.

with the start script:
`parcel src/index.html  --open`
everything runs correctly but in building

`parcel build src/index.html`
I have this error:
```
vec-utils.js:16 Uncaught ReferenceError: regeneratorRuntime is not defined
    at Object.parcelRequire.tKMC (vec-utils.js:16)
    at f (renamer.js:36)
    at p (juxt.js:2)
    at Object.parcelRequire.eh/3../api (index.js:6)
    at f (renamer.js:36)
    at p (juxt.js:2)
    at Object.parcelRequire.XOIc.@thi.ng/vectors (area.js:1)
    at f (renamer.js:36)
    at p (juxt.js:2)
    at Object.parcelRequire.sA42../area (index.js:1)
```

What can it be? I've tried to add `.babelrc` with this content:
```
{
  "plugins": [
    [
      "transform-runtime",
      {
        "polyfill": false,
        "regenerator": true
      }
    ]
  ],
  "presets": [["@babel/env", { "targets": { "firefox": 63, "chrome": 71, "node": 11 } }]]
}
```
as someone advice, but nothing...

I'm using:
`"parcel": "^1.12.2"`

**Comment by postspectacular** [comment]
Isn't regenerator a transform for ES6 generators for ES5? If you're targetting Chrome 71 and FF63, why would you need this? Also, maybe you'll have to add the required [babel plugin](https://www.npmjs.com/package/babel-plugin-transform-regenerator)?

[vec-utils.ts](https://github.com/thi-ng/umbrella/blob/master/packages/vectors/src/internal/vec-utils.ts#L34) contains nothing special, but the 2 generators there might simply be the first ones encountered in the babel code transformation process...

FWIW it's worth, all the examples in the repo are using the following settings in `package.json`, but YMMV:

```json
"browserslist": [
  "last 3 Chrome versions",
  "Firefox 63",
  "Node 11"
],
"browser": {
  "process": false
}
```

Also (probably unrelated), but please see the section about parcel in the [example build instructions](https://github.com/thi-ng/umbrella/wiki/Example-build-instructions#troubleshooting) in the wiki. There's a deeper issue in babel causing the parcel issue... and I've since discovered another one related to tree shaking, but not yet reported.

**Comment by nkint** [comment]
Hi toxi,
thanks for the fast reply.

I don't understand exactly what is happening here (but I admit that don't understand exactly how babel+parcel+browserlist works).

[This is a repo](https://github.com/nkint/umbrella-buid-regenerator-runtime) to reproduce my error.

Other then the wiki page you linked (that I didn't know) I add this two probably related issue:

https://github.com/parcel-bundler/parcel/issues/2128
https://github.com/parcel-bundler/parcel/issues/1762
https://github.com/parcel-bundler/parcel/issues/843

Anyway adding your lines at `package.json` seems to resolve the issue (as I wrote in my test repo).

**Comment by postspectacular** [comment]
@nkint It be great if you could even try a version of an empty project with just a single generator function in the main file and no other runtime dependencies, umbrella or otherwise, e.g.

```
function* foo(x, n) {
   yield "foo";
}

console.log(foo());
```

Will follow up on this later...

**Comment by nkint** [comment]
Just tried, and no error with a simple generator.

I'm using Chrome in Incognito mode and refresh page with hard reload (cmd + shift + r).. but don't really know.

I've also found a [browserlist official repo](https://github.com/browserslist/browserslist)...

**Comment by postspectacular** [comment]
I don't know... the only cause I can think of right now is that all the umbrella packages are distributed in ES6 syntax and it's obvious that babel and/or parcel seems to have some issues with that, even though they both claim to fully support it. AFAIK there's nothing special / non-standard in terms syntax constructs in umbrella and I thankfully never had to deal with this ES5 transpilation mess thus far in practice...

When working on #23 I learned about the browserslist magic, but still have no clue how or where these settings are applied in terms of concrete behavior change in the build chain. None of the tools document this either. I generally really like Parcel, but had to switch back to webpack for production builds of some projects. Also wondering why webpack doesn't have these issues if it also goes via babel under the hood... the amount of magic tooling in the JS world is first mindblowing, then quickly mindnumbing.

**Comment by postspectacular** [comment]
@nkint is this still an ongoing problem for you or can we close this issue?

**Comment by nkint** [comment]
We can close, I never had this problem again after [this browserslist conf](https://github.com/thi-ng/umbrella/issues/78#issuecomment-472805269)
