### ISSUE TITLE
[rstream] StreamCancel is required

### ISSUE THREAD

**Issue by vorg** [thi-ng/umbrella#80]
I was trying to create stream with only one value but the stream [creation example](https://github.com/thi-ng/umbrella/blob/ce74afc55215fee990748c9e7d555a839adcec69/packages/rstream/README.md#stream-creation) with source function doesn't compile

```ts
a = rs.stream((s) => {
    s.next(1);
    s.done();
});
```

with the following error `Argument of type '(s: Stream<{}>) => void' is not assignable to parameter of type 'StreamSource<{}>'.
  Type 'void' is not assignable to type 'StreamCancel'`

Solution, return void function with optional StreamCancel interface declaration

```ts
a = rs.stream((s): StreamCancel => {
    s.next(1);
    s.done();
    return () => {};
});
```

It was confusing as documentation says it's optional ` If the function returns another function, it will be used for cleanup purposes if the stream is cancelled`.

**Comment by postspectacular** [comment]
@vorg thanks - just updated the `StreamSource` type to allow `void` returns from those functions. the docs and implementation were correct, just the type sig was wrong (incomplete). Now fixed in v2.3.2
