### ISSUE TITLE
[rstream] Subscription without last value

### ISSUE THREAD

**Issue by andrew8er** [thi-ng/umbrella#81]
I have a use case, where I do _not_ want `Subscription<A, B>` to remember the last value. I just want to react to events as they happen. Currently I use this:

```ts
class AmnesticSubscriber<A, B> extends Subscription<A, B> {
	protected dispatch(x: B) {
		try {
			super.dispatch(x);
		}
		finally {
			this.last = SEMAPHORE;
		}
	}
}
```

But I do not think this is very elegant. How would this fit into @thi.ng/rstream?

Maybe related: #74

**Comment by postspectacular** [comment]
Hey @andrew8er - so you want to not store it in general or just avoid that new subscribers receive the last value?

**Comment by andrew8er** [comment]
For my particular use case, both approaches would solve the issue. Not storing the value would let the GC reclaim the passed value earlier if it is not referenced elsewhere.

**Comment by postspectacular** [comment]
sorry for the delay @andrew8er - I've been thinking about this and no great obvious solution to disable this yet. Been thinking about introducing ctor options objects (e.g. as done for `StreamSync`) more widely to configure custom behaviors like this. In the interim, one other quick-and-not-so-dirty solution would be to move the `this.last` setter in `dispatch()` into its own method, which you could then override with a blank one.

In `Subscription` class:

```ts
protected dispatch(x: B) {
    this.setValue(x);
    ...
}

protected setValue(x: B) {
    this.last = x;
}
```

Then `AmnesticSubscriber` only needs to:

```ts
class AmnesticSubscriber<A, B> extends Subscription<A, B> {
	protected setValue(x: B) { }
}
```

**Comment by andrew8er** [comment]
Ok, that would be slightly better, but I wonder if it really warrants the extra function call. Maybe I just wait for a more generic solution to this problem, I can live with mine right now.

**Comment by postspectacular** [comment]
Yep, that's what I've been wondering too. Since `dispatch` is a hotspot, I'd really like to keep as barebones as possible...

Let's leave this issue open as mental note. Will create a new issue about potential config options soon...
