### ISSUE TITLE
[geom-isec] pointInSegment2 fails when line is perpendicular

### ISSUE THREAD

**Issue by acarabott** [thi-ng/umbrella#84]
If `a[0] === b[0]` or `a[1] === b[1]` then we get a divide by zero, and will always return `false`.
```ts

const p = [ 5, 10];
const a = [ 0, 10];
const b = [10, 10];

const result = pointInSegment2(p, a, b); // false
```

Also, the check `!(tx < 0 || tx > 1 || ty < 0 || ty > 1)` doesn't take `eps` into account, so the following will return `false`

```ts
const p = [5, 2];
const a = [0, 0];
const b = [10, 1];
const eps = 3;
``` 

as

```ts
const tx = 0.5; // (5 − 0) / (10 − 0)
const ty = 2; // (2 - 0) / (1 - 0)

Math.abs(tx - ty) <= eps; // true (1.5 <= 3)

// but ty > 1 so will return false
```

Pull request coming...

**Comment by acarabott** [comment]
On seconds thoughts, the change to epsilon is not as straightforward as I thought: with a totally horizontal line and an epsilon of (e.g.) `10`, with a point on the line vertically, but outside of it horizontally, it will still return true.

```
a = [ 0, 0]               
b = [10, 0]      
p = [15, 0]
eps = 10

a--------------------b      p


Math.abs(tx - ty): 1.5
tx: 1.5
ty: 0
result: true
```

Input appreciated! Perhaps this approach would work, but would be more expensive: http://paulbourke.net/geometry/pointlineplane/

**Comment by postspectacular** [comment]
Just linking PR comment here: https://github.com/thi-ng/umbrella/pull/85#issuecomment-494340367
