### ISSUE TITLE
[checks] `isMobile` check for Chrome for iOS (`crios`)

### ISSUE THREAD

**Issue by stwind** [thi-ng/umbrella#93]
As said in the [document](https://developer.chrome.com/multidevice/user-agent#chrome_for_ios_user_agent), a typical UA string for Chrome iOS will be something like 
```
Mozilla/5.0 (iPhone; CPU iPhone OS 10_3 like Mac OS X) AppleWebKit/602.1.50 (KHTML, like Gecko) CriOS/56.0.2924.75 Mobile/14E5239e Safari/602.1
```

but there is a negative test for `crios` in [`isMobile`](https://github.com/thi-ng/umbrella/blob/master/packages/checks/src/is-mobile.ts#L4), should it just be a positive one?

**Comment by postspectacular** [comment]
Hi @stwind - i think you might be right here... i took this check from an [old clojurescript project](https://github.com/thi-ng/domus/blob/master/src/detect.org#namespace-thingdomusdetect) of mine but can't remember why this was a neg test...

We could just move the `crios` into the first regexp.. Let me know if you've got time for a PR?! If so, against `develop` branch please...

**Comment by stwind** [comment]
Yeah sure, I'll post a PR for this one later today :)

**Comment by postspectacular** [comment]
Ps. I'm taking a few days off from work next week, so hoping to find time to merge this into master and push new releases...

**Comment by stwind** [comment]
Oh, Thanks a lot @postspectacular
