### ISSUE TITLE
[resolve-map] Trailing commas in object destructuring causes infinite recursion

### ISSUE THREAD

**Issue by tangdrew** [thi-ng/umbrella#97]
## Reproduction
```javascript
const { resolve } = require("@thi.ng/resolve-map");

resolve({
  a: 1,
  b: ({ a, }) => a + 2,
});
```
## Expected
```javascript
// Should return
{
  a: 1,
  b: 3
}
```
## Actual
Throws `RangeError: Maximum call stack size exceeded`

This example where a trailing comma is added to the last destructured property for the argument to the resolve function causes the RangeError. I've identified the [line](https://github.com/thi-ng/umbrella/blob/master/packages/resolve-map/src/index.ts#L243) that causes the issue. When splitting on commas for the destructured argument with a trailing comma, it will try to resolve empty string and enters an infinite loop.

**Comment by postspectacular** [comment]
oh wow - good spotting, @tangdrew! will fix asap. This never occurred to me, since I'm always formatting on "save file" with `prettier` which removes any trailing commas...

**Comment by tangdrew** [comment]
Thanks for the quick response! I prefer no trailing commas as well, but the prettier config a project at work is using has them turned on. Took me a while to track this bug down!

**Comment by postspectacular** [comment]
Published. @thi.ng/resolve-map@4.1.1 - thanks so much for reporting & pinpointing...

**Comment by postspectacular** [comment]
woops! still some more cases where it goes wrong, i.e. if trailing comma AND trailing space(s)

**Comment by postspectacular** [comment]
@thi.ng/resolve-map@4.1.2 - please give it a go... added more tests

**Comment by tangdrew** [comment]
Works! Thanks such a quick turnaround!

**Comment by postspectacular** [comment]
pleasure! ...and just plain ol' good timing!
